-- ============================================================
-- EL CHAT DE «AVISANOS»
--
-- El botón flotante abre un chat que busca entre los trámites y las
-- preguntas frecuentes que el equipo ya cargó. NO es una inteligencia
-- artificial y no inventa nada: si algo no está cargado, dice que no
-- lo tiene y pasa a un compañero de carne y hueso.
--
-- Esa decisión es a propósito. En una app donde la respuesta a «¿hasta
-- cuándo me inscribo?» tiene que ser exacta, un bot que contesta con
-- seguridad algo que se le ocurrió hace más daño que uno que dice «no
-- sé, preguntale a alguien».
--
-- Dos tablas:
--
--   contactos  -> a quién mandarle mensaje cuando el chat no sabe.
--                 Los carga el equipo, los lee todo el mundo.
--   consultas  -> lo que la gente preguntó y el chat no supo contestar.
--                 Las escribe cualquiera, las lee SOLO el equipo.
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada.
-- ============================================================


-- ============================================================
-- 1. LOS CONTACTOS  ·  quién atiende cuando el chat no sabe
-- ============================================================
create table if not exists public.contactos (
  id        bigint generated by default as identity primary key,

  nombre    text not null,                    -- 'Cami'
  carrera   text not null default 'todas',    -- ts | tgcr | fono | todas
  detalle   text,                             -- '4.º año · consejera estudiantil'

  -- Por dónde se le escribe. El enlace lo arma la app: para instagram
  -- va el usuario SIN arroba, para whatsapp el número con código de
  -- país y sin signos, para mail la dirección.
  tipo      text not null default 'instagram',
  destino   text not null,

  activo    boolean not null default true,
  orden     int not null default 0,
  creado_at timestamptz not null default now()
);

create index if not exists contactos_carrera_idx
  on public.contactos (carrera, activo, orden);

alter table public.contactos enable row level security;

grant select on public.contactos to anon, authenticated;
grant insert, update, delete on public.contactos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Cualquiera ve los que están activos, sin cuenta.
drop policy if exists "contactos lectura publica" on public.contactos;
create policy "contactos lectura publica"
  on public.contactos for select
  using (activo = true);

drop policy if exists "contactos el equipo ve todo" on public.contactos;
create policy "contactos el equipo ve todo"
  on public.contactos for select to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "contactos el equipo escribe" on public.contactos;
create policy "contactos el equipo escribe"
  on public.contactos for insert to authenticated
  with check (exists (select 1 from public.perfiles
                      where id = auth.uid() and rol = 'equipo'));

drop policy if exists "contactos el equipo edita" on public.contactos;
create policy "contactos el equipo edita"
  on public.contactos for update to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "contactos el equipo borra" on public.contactos;
create policy "contactos el equipo borra"
  on public.contactos for delete to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));


-- ============================================================
-- 2. LAS CONSULTAS SIN RESPUESTA  ·  lo que falta cargar
--
-- Cada pregunta que el chat no supo contestar queda acá. No es una
-- métrica de vanidad: es la lista de lo que falta en «Info útil»,
-- escrita por los estudiantes con sus palabras.
-- ============================================================
create table if not exists public.consultas (
  id        bigint generated by default as identity primary key,

  texto     text not null,
  carrera   text,          -- si el estudiante la dijo
  pantalla  text,          -- desde qué pantalla preguntó

  resuelta  boolean not null default false,
  creado_at timestamptz not null default now()
);

create index if not exists consultas_pendientes_idx
  on public.consultas (resuelta, creado_at desc);

alter table public.consultas enable row level security;

-- OJO CON ESTE PERMISO: escribe CUALQUIERA, sin cuenta. Tiene que ser
-- así, porque la app se usa entera sin registrarse y el que pregunta
-- casi nunca tiene cuenta.
--
-- Lo que lo hace seguro es lo que NO puede hacer: nadie sin cuenta
-- puede LEER esta tabla, ni editarla, ni borrarla. Solo dejar un
-- renglón.
--
-- OJO, ACÁ HUBO UN AGUJERO (cerrado el 2/9/2026): el `with check`
-- limitaba el largo SOLO de `texto`. Pero `carrera` sale de
-- localStorage y `pantalla` de la URL: las escribe el visitante y no
-- tenían ningún tope. Con eso, un renglón de 500 letras podía traer
-- dos campos de megabytes al lado. La base tiene 500 MB: llenarla es
-- tirar abajo la app entera, no solo Avisanos.
grant insert on public.consultas to anon, authenticated;
grant select, update, delete on public.consultas to authenticated;

drop policy if exists "consultas cualquiera pregunta" on public.consultas;
create policy "consultas cualquiera pregunta"
  on public.consultas for insert to anon, authenticated
  with check (
        char_length(texto) between 2 and 500
    and char_length(coalesce(carrera,  '')) <= 20
    and char_length(coalesce(pantalla, '')) <= 120
    -- Sin esto, quien manda spam lo entra ya marcado como resuelto y
    -- el equipo no lo ve nunca en la lista de pendientes.
    and resuelta = false
  );

-- El freno de caudal. Un tope por renglón no alcanza: lo que llena la
-- base es el bucle, no el renglón. Veinte por minuto es muchísimo más
-- de lo que esta app va a tener, y corta en seco al que automatiza.
--
-- Va como `security definer` porque sin cuenta no se puede leer la
-- tabla, y para contar hay que leerla.
create or replace function public.freno_consultas()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  ultimas int;
begin
  select count(*) into ultimas
    from public.consultas where creado_at > now() - interval '1 minute';
  if ultimas >= 20 then
    raise exception 'Llegaron demasiadas consultas juntas.' using errcode = '54000';
  end if;

  -- Y la misma pregunta repetida, que es lo que hace un botón trabado.
  if exists (select 1 from public.consultas
              where texto = new.texto
                and creado_at > now() - interval '10 minutes') then
    raise exception 'Esa consulta ya llegó recién.' using errcode = '54000';
  end if;

  return new;
end $$;

revoke all on function public.freno_consultas() from public, anon, authenticated;

drop trigger if exists freno_consultas on public.consultas;
create trigger freno_consultas
  before insert on public.consultas
  for each row execute function public.freno_consultas();

drop policy if exists "consultas las lee el equipo" on public.consultas;
create policy "consultas las lee el equipo"
  on public.consultas for select to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "consultas el equipo las marca" on public.consultas;
create policy "consultas el equipo las marca"
  on public.consultas for update to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "consultas el equipo borra" on public.consultas;
create policy "consultas el equipo borra"
  on public.consultas for delete to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));


-- ============================================================
-- Ejemplos, para que el chat no ofrezca una lista vacía.
-- Cámbienlos por gente de verdad y borren estos:
--   delete from public.contactos where detalle = 'EJEMPLO';
-- ============================================================
insert into public.contactos (nombre, carrera, detalle, tipo, destino, orden)
select * from (values
  ('Agrupación Simón Bolívar', 'todas', 'EJEMPLO', 'instagram', 'SimonBolivarfts', 1)
) as v
where not exists (select 1 from public.contactos);

-- Para comprobar que salió bien:
--   select carrera, count(*) from public.contactos where activo group by carrera;
