-- ============================================================
-- LA GUÍA DE UNA MATERIA
--
-- Por ahora hay una sola: Anatomofisiología Fonoaudiológica, de primer
-- año de Fono. La tabla igual lleva carrera y materia_cod: es una
-- columna, no cuesta nada, y si mañana se suma otra materia no hay que
-- rehacer nada. La PANTALLA es a medida de Anatomo.
--
-- Se edita desde el panel, solapa «🧠 Guía de materia».
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada.
-- ============================================================

create table if not exists public.guia_materia (
  id            bigint generated by default as identity primary key,
  carrera       text not null default 'fono',
  materia_cod   text not null,
  materia       text not null,
  anio_programa int,

  bajada        text not null default '',
  equipo        jsonb not null default '[]'::jsonb,   -- ["Prof. Titular: ...", ...]
  contacto      text,

  -- [{ numero, titulo, fechas, contenidos:[...],
  --    modelo:{url,titulo,autor,licencia,fuente,nota} | null,
  --    obligatoria:[...], complementaria:[...] }]
  --
  -- OJO CON "modelo": son modelos 3D de terceros con licencia Creative
  -- Commons. La atribución que muestra la pantalla NO ES OPCIONAL: la
  -- pide la licencia. Si se cambia un modelo, se cambia la atribución.
  modulos       jsonb not null default '[]'::jsonb,

  fechas_clave  jsonb not null default '[]'::jsonb,   -- [{fecha, que}]
  practicos     jsonb not null default '[]'::jsonb,   -- [{titulo, detalle}]
  aprobacion    jsonb not null default '[]'::jsonb,   -- [{titulo, requisitos:[...]}]

  publicado     boolean not null default true,
  actualizado_at timestamptz not null default now()
);

create unique index if not exists guia_materia_unica_idx
  on public.guia_materia (carrera, materia_cod);

alter table public.guia_materia enable row level security;
grant select on public.guia_materia to anon, authenticated;
grant insert, update, delete on public.guia_materia to authenticated;

drop policy if exists "guia lectura publica" on public.guia_materia;
create policy "guia lectura publica" on public.guia_materia for select
  using (publicado = true);

drop policy if exists "guia el equipo ve todo" on public.guia_materia;
create policy "guia el equipo ve todo" on public.guia_materia for select to authenticated
  using (exists (select 1 from public.perfiles where id = auth.uid() and rol = 'equipo'));

drop policy if exists "guia el equipo escribe" on public.guia_materia;
create policy "guia el equipo escribe" on public.guia_materia for insert to authenticated
  with check (exists (select 1 from public.perfiles where id = auth.uid() and rol = 'equipo'));

drop policy if exists "guia el equipo edita" on public.guia_materia;
create policy "guia el equipo edita" on public.guia_materia for update to authenticated
  using (exists (select 1 from public.perfiles where id = auth.uid() and rol = 'equipo'));

drop trigger if exists al_tocar_guia on public.guia_materia;
create trigger al_tocar_guia before update on public.guia_materia
  for each row execute function public.tocar_quienes();

-- El contenido de Anatomofisiología se cargó aparte, transcripto del
-- programa 2026 de la cátedra. Para comprobar:
--   select materia, jsonb_array_length(modulos) from public.guia_materia;
