-- ============================================================
-- EL ORGANIZADOR DE ESTUDIO
--
-- Dos tablas con dueños distintos, y esa es la decisión importante:
--
--   programas      -> los carga EL EQUIPO, una vez, y los lee todo el
--                     mundo. Es el programa oficial de la cátedra.
--   preparaciones  -> las crea CADA ESTUDIANTE para sí. Nadie más las
--                     ve, ni siquiera el equipo.
--
-- Cómo se corre:
--   supabase.com -> proyecto "La Bolivar con vos" -> SQL Editor
--   -> New query -> pegar todo esto -> Run
--
-- Se puede correr más de una vez sin romper nada.
--
-- OJO CON LOS DOS CANDADOS, como en el resto de la app: el GRANT dice
-- si un rol puede tocar la tabla y la RLS dice qué filas. Si solo se
-- escriben las políticas RLS, da error 42501 y no anda nada.
-- ============================================================


-- ============================================================
-- 1. LOS PROGRAMAS  ·  los carga el equipo
-- ============================================================
create table if not exists public.programas (
  id            bigint generated by default as identity primary key,

  carrera       text not null default 'ts',   -- ts | tgcr | fono
  materia_cod   text not null,                -- '211 A', el código del plan
  materia       text not null,                -- 'Trabajo Social I'
  catedra       text,                         -- opcional: qué cátedra
  anio          int,                          -- de qué año es el programa

  -- Las unidades y sus textos, todo junto. Va como jsonb y no en una
  -- tabla aparte porque SIEMPRE se leen y se guardan completos: no hay
  -- ninguna pantalla que pida "un texto suelto".
  --
  -- [ { "titulo": "Unidad 1: El campo profesional",
  --     "textos": [ { "autor": "Carballeda",
  --                   "anio": "2002",
  --                   "titulo": "La intervención en lo social",
  --                   "obligatorio": true } ] } ]
  unidades      jsonb not null default '[]'::jsonb,

  publicado     boolean not null default true,
  creado_at     timestamptz not null default now()
);

-- Una materia puede tener más de un programa (dos cátedras), pero no
-- dos veces el mismo de la misma cátedra y año.
create unique index if not exists programas_unico_idx
  on public.programas (carrera, materia_cod, coalesce(catedra,''), coalesce(anio,0));

alter table public.programas enable row level security;

grant select on public.programas to anon, authenticated;
grant insert, update, delete on public.programas to authenticated;

drop policy if exists "programas lectura publica" on public.programas;
create policy "programas lectura publica"
  on public.programas for select
  using (publicado = true);

drop policy if exists "programas el equipo ve todo" on public.programas;
create policy "programas el equipo ve todo"
  on public.programas for select to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "programas el equipo escribe" on public.programas;
create policy "programas el equipo escribe"
  on public.programas for insert to authenticated
  with check (exists (select 1 from public.perfiles
                      where id = auth.uid() and rol = 'equipo'));

drop policy if exists "programas el equipo edita" on public.programas;
create policy "programas el equipo edita"
  on public.programas for update to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "programas el equipo borra" on public.programas;
create policy "programas el equipo borra"
  on public.programas for delete to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));


-- ============================================================
-- 2. LAS PREPARACIONES  ·  cada estudiante la suya
--
-- ACÁ NO ENTRA EL EQUIPO. Un final que estás preparando, con lo que
-- leíste y lo que te falta, es privado. Las políticas de abajo son
-- por usuario, no por rol: ni siquiera una cuenta de equipo puede ver
-- la preparación de otra persona.
-- ============================================================
create table if not exists public.preparaciones (
  id            bigint generated by default as identity primary key,
  usuario_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,

  carrera       text not null default 'ts',
  materia_cod   text not null,
  materia       text not null,
  mesa_fecha    date,                         -- cuándo es la mesa

  -- Copia editable del programa. Se COPIA a propósito, no se referencia:
  -- si el equipo corrige el programa oficial en octubre, a quien lo está
  -- preparando no se le reescribe el plan por debajo. Y así el estudiante
  -- puede sacar o agregar textos sin tocar el de todos.
  unidades      jsonb not null default '[]'::jsonb,
  programa_id   bigint references public.programas(id) on delete set null,

  -- Qué textos ya leyó: ["u0-t2", "u1-t0"]. Son posiciones dentro de
  -- unidades, así que si edita la lista se recalcula solo.
  leidos        jsonb not null default '[]'::jsonb,

  -- Las metas: cuántos textos por día y desde cuándo escribir.
  -- { "textos_por_dia": 2, "fecha_redaccion": "2026-09-10" }
  metas         jsonb not null default '{}'::jsonb,

  pomodoros     int not null default 0,       -- bloques de 25 min hechos

  creado_at     timestamptz not null default now(),
  actualizado_at timestamptz not null default now()
);

-- Una preparación por materia y por persona: si volvés a prepararla,
-- es la misma y seguís donde estabas.
create unique index if not exists preparaciones_unico_idx
  on public.preparaciones (usuario_id, carrera, materia_cod);

alter table public.preparaciones enable row level security;

grant select, insert, update, delete on public.preparaciones to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "cada uno ve la suya" on public.preparaciones;
create policy "cada uno ve la suya"
  on public.preparaciones for select to authenticated
  using (usuario_id = auth.uid());

drop policy if exists "cada uno crea la suya" on public.preparaciones;
create policy "cada uno crea la suya"
  on public.preparaciones for insert to authenticated
  with check (usuario_id = auth.uid());

drop policy if exists "cada uno edita la suya" on public.preparaciones;
create policy "cada uno edita la suya"
  on public.preparaciones for update to authenticated
  using (usuario_id = auth.uid());

drop policy if exists "cada uno borra la suya" on public.preparaciones;
create policy "cada uno borra la suya"
  on public.preparaciones for delete to authenticated
  using (usuario_id = auth.uid());

-- La fecha de última modificación se pone sola
create or replace function public.tocar_preparacion()
returns trigger language plpgsql as $$
begin
  new.actualizado_at = now();
  return new;
end $$;

drop trigger if exists al_tocar_preparacion on public.preparaciones;
create trigger al_tocar_preparacion before update on public.preparaciones
  for each row execute function public.tocar_preparacion();


-- ============================================================
-- Un programa de EJEMPLO, para que la pantalla no arranque vacía.
-- Bórrenlo cuando carguen los de verdad:
--   delete from public.programas where catedra = 'EJEMPLO';
-- ============================================================
insert into public.programas (carrera, materia_cod, materia, catedra, anio, unidades)
select 'ts', '211 A', 'Trabajo Social I', 'EJEMPLO', 2026, '[
  {"titulo":"Unidad 1: El campo profesional",
   "textos":[
     {"autor":"REVISAR","anio":"","titulo":"Cargar los textos de la unidad 1","obligatorio":true}
   ]},
  {"titulo":"Unidad 2: La intervención",
   "textos":[
     {"autor":"REVISAR","anio":"","titulo":"Cargar los textos de la unidad 2","obligatorio":true}
   ]}
]'::jsonb
where not exists (select 1 from public.programas where catedra = 'EJEMPLO');

-- Para comprobar que salió bien:
--   select materia, catedra, jsonb_array_length(unidades) as unidades from public.programas;
