-- ============================================================
-- MI CURSADA, MIS FALTAS Y EL MODO ÉPOCA DE PARCIALES
--
-- La ronda 2 del rediseño de la agenda (18/9/2026). Hasta acá la
-- agenda solo mostraba lo que publica el equipo; esto son eventos
-- PROPIOS de cada estudiante. Tres tablas, las tres privadas:
--
--   cursada       -> en qué día y bloque cursa cada materia
--   falta         -> una fila por cada vez que faltó
--   preferencias  -> si el modo época de parciales está prendido y
--                    qué categorías deja visibles
--
-- ACÁ NO ENTRA EL EQUIPO, igual que en `preparaciones`: las políticas
-- son por usuario, no por rol.
--
-- Cómo se corre:
--   supabase.com -> proyecto "La Bolivar con vos" -> SQL Editor
--   -> New query -> pegar todo esto -> Run
-- Se puede correr más de una vez sin romper nada.
--
-- Los dos candados, como en el resto de la app: el GRANT dice si un
-- rol puede tocar la tabla y la RLS dice qué filas.
-- ============================================================


-- ============================================================
-- 1. LA CURSADA
--
-- Una fila = una materia en un día y un bloque. Si una materia se
-- cursa dos veces por semana, son dos filas con el mismo nombre.
-- Una celda de la semana tiene UNA clase: de ahí el índice único.
-- ============================================================
create table if not exists public.cursada (
  id            bigint generated by default as identity primary key,
  usuario_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,

  materia       text not null check (length(trim(materia)) > 0),
  dia           smallint not null check (dia between 1 and 7),       -- 1 = lunes
  bloque        text not null check (bloque in ('manana','tarde','noche')),
  hora          text,                                                 -- '18:00'
  aula          text,
  -- Clases del cuatrimestre. El tope de faltas sale de acá:
  -- floor(total_clases * 0.2), que es el 80% de presentismo.
  total_clases  int not null default 16 check (total_clases between 0 and 200),

  creado_at     timestamptz not null default now()
);

create unique index if not exists cursada_celda_idx
  on public.cursada (usuario_id, dia, bloque);


-- ============================================================
-- 2. LAS FALTAS
--
-- NO HAY CONTADOR GUARDADO. «Te quedan 3» sale de contar filas: un
-- número guardado se desincroniza, y ahí el estudiante pierde la
-- regularidad creyendo que le quedaba una. «Falté» es un insert,
-- «Deshacer» borra la última.
--
-- Va por nombre de materia y no por fila de cursada: una materia de
-- dos días por semana tiene un solo tope de faltas, no dos.
-- ============================================================
create table if not exists public.falta (
  id            bigint generated by default as identity primary key,
  usuario_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  materia       text not null check (length(trim(materia)) > 0),
  fecha         date not null default current_date,
  creado_at     timestamptz not null default now()
);

create index if not exists falta_materia_idx
  on public.falta (usuario_id, materia);


-- ============================================================
-- 3. LAS PREFERENCIAS
--
-- Va en una tabla propia y no como columna de `perfiles` a propósito:
-- para que cada uno pudiera escribir su preferencia en `perfiles`
-- habría que dejarle editar su fila, y en esa fila está `rol`.
--
-- Las categorías visibles nunca pueden quedar en cero: una agenda
-- vacía por un filtro olvidado es la forma más fácil de perder un
-- final. Por defecto quedan las dos académicas.
-- ============================================================
create table if not exists public.preferencias (
  usuario_id    uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  enfoque       boolean not null default false,
  enfoque_cats  jsonb not null default '["info","saberes"]'::jsonb
                check (jsonb_typeof(enfoque_cats) = 'array'
                       and jsonb_array_length(enfoque_cats) >= 1),
  actualizado_at timestamptz not null default now()
);


-- ============================================================
-- 4. LOS CANDADOS
-- ============================================================
alter table public.cursada      enable row level security;
alter table public.falta        enable row level security;
alter table public.preferencias enable row level security;

-- `anon` no tiene nada que hacer acá: sin cuenta no hay cursada.
revoke all on public.cursada, public.falta, public.preferencias from anon;
grant select, insert, update, delete on public.cursada, public.falta, public.preferencias
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare t text;
begin
  foreach t in array array['cursada','falta','preferencias'] loop
    execute format('drop policy if exists "cada uno ve lo suyo" on public.%I', t);
    execute format('create policy "cada uno ve lo suyo" on public.%I
      for select to authenticated using (usuario_id = (select auth.uid()))', t);

    execute format('drop policy if exists "cada uno agrega lo suyo" on public.%I', t);
    execute format('create policy "cada uno agrega lo suyo" on public.%I
      for insert to authenticated with check (usuario_id = (select auth.uid()))', t);

    execute format('drop policy if exists "cada uno edita lo suyo" on public.%I', t);
    execute format('create policy "cada uno edita lo suyo" on public.%I
      for update to authenticated using (usuario_id = (select auth.uid()))
      with check (usuario_id = (select auth.uid()))', t);

    execute format('drop policy if exists "cada uno borra lo suyo" on public.%I', t);
    execute format('create policy "cada uno borra lo suyo" on public.%I
      for delete to authenticated using (usuario_id = (select auth.uid()))', t);
  end loop;
end $$;
