-- ============================================================
-- EL REGISTRO  ·  para saber qué le pasa a la app
--
-- Hasta el 4/9/2026 la app no anotaba nada. Si algo se rompía en
-- un teléfono ajeno, no nos enterábamos nunca; y si alguien
-- preguntaba cuánta gente entró, no había respuesta. El día del
-- lanzamiento eso es la diferencia entre saber y suponer.
--
-- Se anotan tres cosas: las visitas, lo que la gente busca y lo
-- que se rompe. Se miran desde el panel, en la solapa «Registro».
--
-- LO QUE NO SE GUARDA, a propósito: no hay columna de usuario, ni
-- de dirección de internet, ni nada que permita unir dos visitas
-- de la misma persona. Del aparato queda un balde grueso
-- —iphone, android, escritorio— que alcanza para saber dónde se
-- rompió algo y no alcanza para reconocer a nadie.
--
-- Y es una puerta que escribe SIN CUENTA, igual que las consultas
-- de Avisanos, así que nace con lo mismo: topes por fila y freno
-- de caudal. Una tabla de registro sin freno es la forma más
-- fácil que hay de llenar una base.
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada.
-- ============================================================

create table if not exists public.sucesos (
  id          bigint generated by default as identity primary key,
  tipo        text not null,      -- visita | error | busqueda
  pantalla    text,               -- de qué pantalla salió
  detalle     text,               -- el término buscado, o el error
  dispositivo text,               -- iphone | android | escritorio | otro
  creado_at   timestamptz not null default now()
);

alter table public.sucesos drop constraint if exists sucesos_validos;
alter table public.sucesos add constraint sucesos_validos check (
      tipo in ('visita','error','busqueda')
  and char_length(coalesce(pantalla,   '')) <= 120
  and char_length(coalesce(detalle,    '')) <= 300
  and coalesce(dispositivo,'otro') in ('iphone','android','escritorio','otro')
);

create index if not exists sucesos_tipo_idx  on public.sucesos (tipo, creado_at desc);
create index if not exists sucesos_fecha_idx on public.sucesos (creado_at desc);

alter table public.sucesos enable row level security;

-- Sin cuenta SOLO se puede anotar. Ni leer, ni editar, ni borrar.
revoke insert, update, delete on public.sucesos from anon;
grant insert on public.sucesos to anon;
grant insert, select, delete on public.sucesos to authenticated;

drop policy if exists "sucesos cualquiera anota" on public.sucesos;
create policy "sucesos cualquiera anota"
  on public.sucesos for insert to anon, authenticated
  with check (true);

drop policy if exists "sucesos los lee el equipo" on public.sucesos;
create policy "sucesos los lee el equipo"
  on public.sucesos for select to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "sucesos el equipo borra" on public.sucesos;
create policy "sucesos el equipo borra"
  on public.sucesos for delete to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));


-- ============================================================
-- EL FRENO, Y LA LIMPIEZA SOLA
--
-- El tope es alto a propósito: 600 por minuto, o sea diez por
-- segundo. Un registro que se corta justo el día del pico no
-- sirve para nada, y el 21 el pico ES el punto. Igual frena en
-- seco a quien automatice.
--
-- La limpieza va acá y no en una tarea programada porque no hay
-- ninguna configurada en el proyecto: una vez cada mil
-- inserciones borra lo que tenga más de noventa días. Sale gratis
-- y nadie tiene que acordarse.
-- ============================================================
create or replace function public.freno_sucesos()
returns trigger language plpgsql security definer set search_path = public as $$
declare ultimos int;
begin
  select count(*) into ultimos
    from public.sucesos where creado_at > now() - interval '1 minute';
  if ultimos >= 600 then
    raise exception 'Demasiados sucesos por minuto.' using errcode = '54000';
  end if;

  if random() < 0.001 then
    delete from public.sucesos where creado_at < now() - interval '90 days';
  end if;

  return new;
end $$;

revoke all on function public.freno_sucesos() from public, anon, authenticated;

drop trigger if exists freno_sucesos on public.sucesos;
create trigger freno_sucesos
  before insert on public.sucesos
  for each row execute function public.freno_sucesos();


-- ============================================================
-- EL RESUMEN QUE MIRA EL PANEL
--
-- Las cuentas las hace la base y manda un solo objeto. La
-- alternativa era bajarse miles de filas al navegador para
-- sumarlas ahí, que es justo lo que le estuvimos sacando a la app.
--
-- Es `security definer` porque necesita leer la tabla entera,
-- pero lo PRIMERO que hace es comprobar que quien llama sea del
-- equipo. Sin eso, cualquiera con cuenta de estudiante leería las
-- búsquedas y los errores de todo el mundo.
-- ============================================================
create or replace function public.resumen_registro()
returns jsonb language plpgsql security definer set search_path = public as $$
declare r jsonb;
begin
  if not exists (select 1 from public.perfiles
                  where id = auth.uid() and rol = 'equipo') then
    raise exception 'Solo el equipo puede ver el registro.' using errcode = '42501';
  end if;

  with dias as (
    select date_trunc('day', creado_at) as d, count(*) as n
      from public.sucesos
     where tipo = 'visita' and creado_at >= now() - interval '14 days'
     group by 1
  ),
  busq as (
    select detalle as texto, count(*) as n
      from public.sucesos
     where tipo = 'busqueda' and creado_at >= now() - interval '30 days'
       and detalle is not null
     group by 1
  ),
  errs as (
    select detalle as texto, count(*) as n, max(creado_at) as ultima,
           string_agg(distinct dispositivo, ', ') as aparatos
      from public.sucesos
     where tipo = 'error' and creado_at >= now() - interval '30 days'
       and detalle is not null
     group by 1
  ),
  pant as (
    select coalesce(pantalla, '-') as pantalla, count(*) as n
      from public.sucesos
     where tipo = 'visita' and creado_at >= now() - interval '7 days'
     group by 1
  )
  select jsonb_build_object(
    'visitas_hoy', (select count(*) from public.sucesos
                     where tipo='visita' and creado_at >= date_trunc('day', now())),
    'visitas_7d',  (select count(*) from public.sucesos
                     where tipo='visita' and creado_at >= now() - interval '7 days'),
    'errores_7d',  (select count(*) from public.sucesos
                     where tipo='error'  and creado_at >= now() - interval '7 days'),
    'busquedas_7d',(select count(*) from public.sucesos
                     where tipo='busqueda' and creado_at >= now() - interval '7 days'),
    'por_dia',   (select coalesce(jsonb_agg(jsonb_build_object(
                    'dia', to_char(d,'DD/MM'), 'n', n) order by d), '[]'::jsonb) from dias),
    'pantallas', (select coalesce(jsonb_agg(jsonb_build_object(
                    'pantalla', pantalla, 'n', n) order by n desc), '[]'::jsonb) from pant),
    'busquedas', (select coalesce(jsonb_agg(jsonb_build_object(
                    'texto', texto, 'n', n) order by n desc, texto), '[]'::jsonb) from busq),
    'errores',   (select coalesce(jsonb_agg(jsonb_build_object(
                    'texto', texto, 'n', n, 'aparatos', aparatos,
                    'ultima', to_char(ultima,'DD/MM HH24:MI')) order by n desc), '[]'::jsonb) from errs)
  ) into r;

  return r;
end $$;

revoke all on function public.resumen_registro() from public, anon;
grant execute on function public.resumen_registro() to authenticated;

-- Para comprobar a mano qué se anotó:
--   select tipo, count(*) from public.sucesos group by 1;
