-- ============================================================
-- LA TABLA PARA "ESTUDIEMOS"
--
-- Guarda el material de los grupos de estudio: apuntes, resúmenes,
-- parciales viejos, programas, guías.
--
-- Cómo se corre:
--   supabase.com -> proyecto "La Bolivar con vos" -> SQL Editor
--   -> New query -> pegar todo esto -> Run
--
-- Se puede correr más de una vez sin romper nada.
--
-- OJO CON LOS DOS CANDADOS: como está explicado en el LEEME, hacen
-- falta los dos. El GRANT decide si un rol puede tocar la tabla y la
-- RLS decide qué filas. Si solo se escriben las políticas RLS, no
-- funciona nada y da un error 42501.
-- ============================================================

create table if not exists public.materiales (
  id           bigint generated by default as identity primary key,

  titulo       text not null,          -- "Resumen de la unidad 3"
  materia      text not null,          -- "Trabajo Social I". Agrupa la pantalla.
  catedra      text,                   -- opcional: qué cátedra
  tipo         text not null default 'apunte',
                                       -- apunte | resumen | parcial | programa | guia | otro
  descripcion  text,                   -- de qué se trata, en dos renglones
  link_url     text,                   -- a Drive, a un PDF, a donde sea
  link_titulo  text,                   -- lo que dice el botón
  aporta       text,                   -- quién lo compartió, si lo quieren decir
  anio         int,                    -- de qué año es el material

  publicado    boolean not null default true,
  orden        int not null default 0,
  creado_at    timestamptz not null default now()
);

-- Para que la pantalla ordene rápido por materia
create index if not exists materiales_materia_idx
  on public.materiales (materia, orden, id);

-- ---------- CANDADO 1: los permisos de la tabla ----------
alter table public.materiales enable row level security;

grant select on public.materiales to anon, authenticated;
grant insert, update, delete on public.materiales to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------- CANDADO 2: qué filas ve y toca cada quien ----------

-- Cualquiera puede LEER lo que esté publicado, sin cuenta.
drop policy if exists "materiales lectura publica" on public.materiales;
create policy "materiales lectura publica"
  on public.materiales for select
  using (publicado = true);

-- El equipo ve todo, incluso lo que todavía no publicó.
drop policy if exists "materiales el equipo ve todo" on public.materiales;
create policy "materiales el equipo ve todo"
  on public.materiales for select to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

-- Solo el equipo carga, edita y borra. Una cuenta de estudiante que
-- lo intente afecta 0 filas, igual que en el resto de las tablas.
drop policy if exists "materiales el equipo escribe" on public.materiales;
create policy "materiales el equipo escribe"
  on public.materiales for insert to authenticated
  with check (exists (select 1 from public.perfiles
                      where id = auth.uid() and rol = 'equipo'));

drop policy if exists "materiales el equipo edita" on public.materiales;
create policy "materiales el equipo edita"
  on public.materiales for update to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

drop policy if exists "materiales el equipo borra" on public.materiales;
create policy "materiales el equipo borra"
  on public.materiales for delete to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'));

-- ============================================================
-- Dos ejemplos, para que la pantalla no arranque vacía.
-- Bórrenlos cuando carguen material de verdad:
--   delete from public.materiales where aporta = 'EJEMPLO';
-- ============================================================
insert into public.materiales
  (titulo, materia, tipo, descripcion, link_titulo, link_url, aporta, anio, orden)
select 'Grupo de estudio: Trabajo Social I', 'Trabajo Social I', 'guia',
       'REVISAR: de qué se trata el grupo, cuándo se junta y cómo sumarse.',
       'Sumarme', null, 'EJEMPLO', 2026, 1
where not exists (select 1 from public.materiales where aporta = 'EJEMPLO');

insert into public.materiales
  (titulo, materia, tipo, descripcion, link_titulo, link_url, aporta, anio, orden)
select 'Resumen de la unidad 1', 'Epistemología de las Ciencias Sociales', 'resumen',
       'REVISAR: qué cubre el resumen y quién lo armó.',
       'Ver el resumen', null, 'EJEMPLO', 2026, 2
where (select count(*) from public.materiales where aporta = 'EJEMPLO') < 2;

-- Para comprobar que salió bien:
--   select materia, count(*) from public.materiales group by materia;
