-- ============================================================
-- LOS CONTACTOS DE LAS CÁTEDRAS
--
-- A quién le escribís si tenés una duda de una materia. Hasta ahora
-- eso se averiguaba preguntando en un grupo de WhatsApp.
--
-- SE ATA POR CÓDIGO, NO POR NOMBRE. `materia_cod` es el código tal
-- cual figura en el plan ('211 A', '811', '212 A'), que es el mismo
-- que usa `carrera/plan.js`. Atar por nombre no funcionaba: los mails
-- vinieron abreviados —«Epis», «Intro a la psico», «Inves I»— y el
-- plan los tiene completos. Por código enganchan los 75.
--
-- UNA MATERIA COMPARTIDA ES DOS FILAS. «Salud Colectiva» (253) la
-- cursan Trabajo Social y Fonoaudiología, y es la misma cátedra con
-- los mismos mails. Van dos filas igual, una por carrera: así la
-- pantalla filtra por la carrera de la persona sin pensar, y el día
-- que una carrera cambie de cátedra no hay que desarmar nada.
--
-- LOS MAILS SON PÚBLICOS. Son direcciones institucionales de cátedra
-- que ya están publicadas en la página de la facultad. No hay acá
-- ningún dato que no esté a la vista.
--
-- Cómo se corre:
--   supabase.com -> proyecto "La Bolivar con vos" -> SQL Editor
--   -> New query -> pegar todo esto -> Run
-- Se puede correr más de una vez sin romper nada.
--
-- OJO CON LOS DOS CANDADOS, como el resto de las tablas: el GRANT
-- decide si un rol puede tocar la tabla y la RLS decide qué filas.
-- Solo con las políticas RLS no funciona nada y da un error 42501.
-- ============================================================

create table if not exists public.catedras (
  id             bigint generated by default as identity primary key,

  carrera        text not null,          -- ts | fono | tgcr
  materia_cod    text not null,          -- '211 A', '811'. Ata con plan.js
  materia        text not null,          -- nombre completo, para leer y buscar

  mails          text[] not null default '{}',
  telefono       text,                   -- casi ninguna lo tiene
  nota           text,                   -- "el contacto está sin confirmar", etc.

  /* El año en que se cursa. Está acá y no se saca de `plan.js` para
     que la pantalla de Cátedras pueda agrupar por año sin bajar los
     tres planes: son 20 KB para un solo dato. Sale de los planes, que
     siguen siendo la fuente si alguna vez cambian. */
  anio           smallint,

  publicado      boolean not null default true,
  actualizado_at timestamptz not null default now(),

  unique (carrera, materia_cod)
);

/* Por si la tabla ya existía de antes de que se agregara el año. */
alter table public.catedras add column if not exists anio smallint;

alter table public.catedras drop constraint if exists catedras_validas;
alter table public.catedras add constraint catedras_validas check (
      carrera in ('ts','fono','tgcr')
  and char_length(materia_cod) between 1 and 20
  and char_length(materia)     between 1 and 200
  and coalesce(array_length(mails, 1), 0) <= 8
  and char_length(coalesce(telefono, '')) <= 40
  and char_length(coalesce(nota,     '')) <= 300
  and (anio is null or anio between 1 and 5)
);

create index if not exists catedras_carrera_idx on public.catedras (carrera, materia_cod);

alter table public.catedras enable row level security;

-- ---------- Candado 1: los GRANT ----------
-- Sin cuenta SOLO se lee. Ni insertar, ni editar, ni borrar.
revoke insert, update, delete on public.catedras from anon;
grant select on public.catedras to anon;
grant select, insert, update, delete on public.catedras to authenticated;

-- ---------- Candado 2: las políticas ----------
drop policy if exists "catedras las lee cualquiera" on public.catedras;
create policy "catedras las lee cualquiera"
  on public.catedras for select to anon, authenticated
  using (publicado = true);

drop policy if exists "catedras las edita el equipo" on public.catedras;
create policy "catedras las edita el equipo"
  on public.catedras for all to authenticated
  using (exists (select 1 from public.perfiles
                 where id = auth.uid() and rol = 'equipo'))
  with check (exists (select 1 from public.perfiles
                      where id = auth.uid() and rol = 'equipo'));


-- ============================================================
-- LA CARGA
--
-- Material entregado por Máximo el 4/9/2026. El crudo, sin tocar,
-- está en `contenido-catedras.md`.
--
-- `on conflict` actualiza: si se corre de nuevo con un mail
-- corregido, pisa el viejo y no duplica.
-- ============================================================

insert into public.catedras (carrera, materia_cod, materia, mails) values

-- ---------------- TRABAJO SOCIAL ----------------
('ts','211 A','Trabajo Social I', array['trabajosocial1unlp@gmail.com','alfredocarballeda@gmail.com','josescelsio@yahoo.com.ar']),
('ts','214','Historia Social de América Latina y Argentina', array['matiasbisso@yahoo.com.ar','nbragagnolo@yahoo.com.ar']),
('ts','213','Epistemología de las Ciencias Sociales', array['fernandomartingallego@yahoo.com.ar','fj_gulino@yahoo.com.ar']),
('ts','215 A','Introducción a la Teoría Social', array['segura.ramiro@gmail.com','moyhandy@yahoo.com.ar']),
('ts','212 A','Introducción a la Filosofía', array['filosofia.fts@trabajosocial.unlp.edu.ar','santiago.liaudat@gmail.com','juanmanuelfontana@yahoo.com.ar']),
('ts','211 B','Configuración de los Problemas Sociales', array['configuraciondeproblemassociales@yahoo.com','laura_massa@hotmail.com','mvelurtas@yahoo.com']),
('ts','221','Trabajo Social II', array['catedratrabajo2@gmail.com','claudiodanielrios@hotmail.com','vickyterzaghi@hotmail.com','agustinafavero@hotmail.com']),
('ts','225','Teoría Social', array['julsarmiento@gmail.com','chcastillo2002@yahoo.com.ar']),
('ts','222','Investigación Social I', array['mvbranca@gmail.com','cuencadriana@yahoo.com.ar','cuencadriana59@gmail.com']),
('ts','215 B','Teoría de las culturas y antropologías de las sociedades contemporáneas', array['teoriasdelacultura@trabajosocial.unlp.edu.ar','nestorarti@hotmail.com','elenaberge@gmail.com']),
('ts','223','Introducción a la Psicología', array['introduccionpsicologiafts@gmail.com','ro.fischquin@gmail.com','cynlaplata@yahoo.com.ar']),
('ts','226','Teoría del Estado', array['teoriadelestadofts@gmail.com']),
('ts','227','Economía Política', array['fabflores@yahoo.com','sergiodumrauf@yahoo.com.ar']),
('ts','231','Trabajo Social III', array['silvinacavalleri@hotmail.com','saladaniela@gmail.com','silpantanali@yahoo.com.ar']),
('ts','234','Conformación de la Estructura Social Argentina', array['estructurasocialfts@gmail.com','mdiloretto@gmail.com','juanignaciolozano@yahoo.com.ar']),
('ts','242','Política Social', array['politica@trabajosocial.unlp.edu.ar','mgabrinetti@yahoo.com.ar','matiasiu3@gmail.com']),
('ts','237','Trabajo Social y Sujetos Colectivos', array['elopez@trabajosocial.unlp.edu.ar','zulmahallak@yahoo.com.ar']),
('ts','224','Perspectivas antropológicas para la intervención social', array['antropologia2@trabajosocial.unlp.edu.ar','adecolangelo@yahoo.com.ar','irobia@yahoo.com.ar']),
('ts','232','Investigación Social II', array['Investigacionsocial2fts@gmail.com','patricia.schettini@gmail.com','lourdesfarias_mpd@yahoo.com']),
('ts','241','Trabajo Social IV', array['tsocialiv.ftsunlp@gmail.com','pilifuentes08@gmail.com','lzucherino@hotmail.com','clarawebers@yahoo.com.ar']),
('ts','243','Trabajo Social y Análisis Institucional', array['tsinstitucional@gmail.com','danelpaula@hotmail.com']),
('ts','233','Psicología del desarrollo y la Subjetividad', array['silvinarivas@hotmail.com','gabrielaroitstein@gmail.com']),
('ts','244','Teoría y Práctica de la Educación', array['teoriaypracticaeducacion@gmail.com','gabrielasprella@gmail.com','cesargeronimotello@yahoo.com.ar']),
('ts','245','Teoría del Derecho y Derecho Social', array['rodolfo.alberto.sosa@gmail.com','marianocardelli@gmail.com']),
('ts','235','Derecho de infancia, familia y cuestión penal', array['jmi02@hotmail.com','gabrielvitale@gmail.com','cyabalos@yahoo.com.ar']),
('ts','253','Salud Colectiva', array['saludcolectivafts@gmail.com','gsusanlopez@hotmail.com','michelliv@yahoo.com']),
('ts','251','Trabajo Social V', array['tsocial5.fts@gmail.com','marinacappello2@gmail.com','marinacapello@yahoo.com.ar','cmamblona@yahoo.com.ar','varedondi@yahoo.com']),
('ts','252','Políticas Públicas: Planificación y Gestión', array['admitrabajosocial@yahoo.com.ar','mariabonicattogrillo@gmail.com','analiabch@hotmail.com']),
('ts','212 B','Filosofía Social', array['filosofiasocialfts@gmail.com','germanromoli@hotmail.com']),
('ts','254','Debate contemporáneo y Trabajo Social', array['debatecontemporaneots@gmail.com','veronica.cruz09@yahoo.com.ar','mnoelialopez1981@gmail.com']),

-- ---------------- FONOAUDIOLOGÍA ----------------
('fono','811','Ontología del lenguaje y la comunicación humana', array['ontologia.fts@gmail.com']),
('fono','812','Fundamentos de la fonoaudiología', array['fundamentosdelafonoaudiologia@gmail.com']),
('fono','813','Epistemología', array['zolkower@yahoo.com.ar']),
('fono','814','Anatomofisiología fonoaudiológica', array['ftsmalvinacastillo@gmail.com']),
('fono','815','Acústica', array['acusticafonofts@gmail.com']),
('fono','223','Introducción a la psicología', array['introduccionpsicologiafts@gmail.com']),
('fono','816','Bases neuropsicológicas de la comunicación', array['bnpscomunicacion.unlp@gmail.com']),
('fono','817','Lingüística', array['linguisticafts@gmail.com']),
('fono','818','Sociología', array['sociologiafonofts@gmail.com']),
('fono','212 A','Introducción a la filosofía', array['filosofia.fts@trabajosocial.unlp.edu.ar']),
('fono','821','Procesos lingüísticos y comunicación', array['mscesanelli@gmail.com','marinabirocho@gmail.com','jackylinares24@gmail.com']),
('fono','822','Función fonatoria y comunicación', array['nerinakildau@gmail.com','funcionfonatoria.unlp@gmail.com']),
('fono','823','Teoría de la comunicación', array['gfzubia@gmail.com','demartinojuliane@gmail.com','debora.antonella.luna@gmail.com']),
('fono','824','Audiología y comunicación', array['karinacittadino@hotmail.com','audiologiaunlp@gmail.com']),
('fono','825','Desarrollo de la función oral faríngea', array['giselepradofono@gmail.com','dfof2022@gmail.com']),
('fono','826','Fonética y fonología', array['melina.d.gaona@gmail.com','ludmilabarbero@gmail.com','paulymachicote@gmail.com']),
('fono','827','Metodología de la investigación', array['cingolanijosefina@gmail.com']),
('fono','828','Acciones y prácticas en audiología', array['karinacittadino@hotmail.com']),
('fono','215 B','Teorías de las culturas y antropología de las sociedades contemporáneas', array['teoriasdelacultura@trabajosocial.unlp.edu.ar']),
('fono','512','Salud fonatoria', array['saludfonatoriafts@gmail.com']),
('fono','532','Lenguaje infantil e intervención fonoaudiológica', array['catedralenguajeinfantil.fts@gmail.com']),
('fono','523','Abordaje terapéutico del sistema vestibular', array['mariaclaudiaterrerosariza@gmail.com','abordajesistemavestibular@gmail.com']),
('fono','253','Salud colectiva', array['saludcolectivafts@gmail.com','gsusanlopez@hotmail.com','michelliv@yahoo.com']),
('fono','831','Introducción al análisis de la estructura social argentina', array['intestructurasocial@gmail.com']),
('fono','832','Fonoaudiología, derechos humanos y género', array['fonoddhhygenero@gmail.com']),
('fono','244','Teoría y práctica de la educación', array['teoriaypracticaeducacion@gmail.com','gabrielasprella@gmail.com','cesargeronimotello@yahoo.com.ar']),
('fono','233','Psicología del desarrollo y la subjetividad', array['silvinarivas@hotmail.com','gabrielaroitstein@gmail.com']),
('fono','841','Campos de intervención profesional - práctica territorial', array['alejandrabulich@gmail.com']),
('fono','842','Voz y habla de la comunicación y el trabajo', array['claudiadiaz_85@hotmail.com']),
('fono','843','Política social', array['mgabrinetti@yahoo.com.ar']),
('fono','844','Fonoaudiología en ámbitos educativos', array['valeriaperilli@yahoo.com.ar']),
('fono','846','Fonoaudiología en atención primaria de la salud', array['ana.e.fuks@gmail.com']),

-- ---------------- TECNICATURA EN GESTIÓN COMUNITARIA DEL RIESGO ----------------
('tgcr','711','Estado, territorio y problemática social', array['lucianaponz2015@gmail.com']),
('tgcr','712','Gestión del riesgo y matrices del desarrollo', array['pablodiotto66@gmail.com']),
('tgcr','713','Riesgo, conflictos territoriales y cambio climático', array['brunoelcarpincho@hotmail.com']),
('tgcr','717','Educación Popular y organización comunitaria', array['alejandrabulich@gmail.com']),
('tgcr','721','Intervención Social I', array['mlviscardi@gmail.com']),
('tgcr','722','Gestión del riesgo I', array['martinmigueltorres@gmail.com']),
('tgcr','723','Salud y epidemiología sociocultural', array['gsusanlopez@hotmail.com']),
('tgcr','724','Territorio y estrategias de comunicación', array['arruavanesa@gmail.com']),
('tgcr','731','Intervención social II', array['sperdoni64@yahoo.com']),
('tgcr','732','Seguridad humana y procesos comunitarios', array['fajgarcia@gmail.com']),
('tgcr','733','Normativas para la seguridad humana', array['luis.federico.arias@gmail.com']),
('tgcr','734','Trabajo social en gestión del riesgo', array['marcelasanchez785@gmail.com'])

on conflict (carrera, materia_cod) do update
  set materia        = excluded.materia,
      mails          = excluded.mails,
      actualizado_at = now();


-- ---------- La que tiene el teléfono suelto ----------
-- «Acciones para la salud fonoestomatológica» vino con un mail Y un
-- número. El número va en su columna, no mezclado entre los mails.
insert into public.catedras (carrera, materia_cod, materia, mails, telefono) values
('fono','829','Acciones para la salud fonoestomatológica',
 array['giselepradofono@gmail.com'], '11 4916-4297')
on conflict (carrera, materia_cod) do update
  set mails          = excluded.mails,
      telefono       = excluded.telefono,
      actualizado_at = now();


-- ---------- Las tres que quedaron SIN publicar ----------
--
-- Se cargan igual, pero con `publicado = false`: así están anotadas
-- para el panel y NO se muestran en la app. Un contacto que rebota es
-- peor que no tener contacto.
--
--   514  el único mail que vino —«promoción y prevención»— lleva
--        tildes, y la parte local de una dirección de Gmail no las
--        acepta: esa casilla no existe. Falta que la confirmen.
--   513  y  848  vinieron sin ningún mail.
--
-- Cuando Máximo confirme, se corrige acá, se pone `publicado = true`
-- y se corre de nuevo.
insert into public.catedras (carrera, materia_cod, materia, mails, nota, publicado) values
('fono','514','Promoción y prevención en audiología', array[]::text[],
 'El mail que nos pasaron lleva tildes y por eso no puede existir. Falta confirmarlo.', false),
('fono','513','Intervención del lenguaje en población adulta', array[]::text[],
 'Todavía no tenemos el contacto.', false),
('fono','848','Taller de metodología II', array[]::text[],
 'Todavía no tenemos el contacto. Ojo: nos lo pasaron como de 3° año, y en el plan el II es de 4°; el de 3° es el Taller I (833).', false)
on conflict (carrera, materia_cod) do nothing;


-- ---------- El año de cada materia ----------
-- Sale de `carrera/plan.js`, `plan-fono.js` y `plan-tgcr.js`, que
-- siguen siendo la fuente. Se copia acá para que la pantalla de
-- Cátedras agrupe por año sin bajar los tres planes.
update public.catedras c set anio = v.anio
  from (values
    ('ts','211 A',1),('ts','214',1),('ts','215 A',1),('ts','213',1),('ts','211 B',1),('ts','212 A',1),
    ('ts','221',2),('ts','225',2),('ts','222',2),('ts','215 B',2),('ts','223',2),('ts','226',2),('ts','227',2),
    ('ts','231',3),('ts','234',3),('ts','242',3),('ts','237',3),('ts','224',3),('ts','232',3),
    ('ts','241',4),('ts','243',4),('ts','233',4),('ts','244',4),('ts','235',4),('ts','245',4),('ts','253',4),
    ('ts','251',5),('ts','252',5),('ts','212 B',5),('ts','254',5),
    ('fono','811',1),('fono','812',1),('fono','813',1),('fono','814',1),('fono','815',1),('fono','223',1),
    ('fono','816',1),('fono','817',1),('fono','818',1),('fono','212 A',1),
    ('fono','821',2),('fono','822',2),('fono','823',2),('fono','824',2),('fono','825',2),('fono','826',2),
    ('fono','827',2),('fono','828',2),('fono','829',2),('fono','215 B',2),
    ('fono','512',3),('fono','532',3),('fono','523',3),('fono','253',3),('fono','831',3),('fono','832',3),
    ('fono','513',3),('fono','514',3),('fono','244',3),('fono','233',3),
    ('fono','841',4),('fono','842',4),('fono','843',4),('fono','844',4),('fono','846',4),('fono','848',4),
    ('tgcr','711',1),('tgcr','712',1),('tgcr','713',1),('tgcr','717',1),
    ('tgcr','721',2),('tgcr','722',2),('tgcr','723',2),('tgcr','724',2),
    ('tgcr','731',3),('tgcr','732',3),('tgcr','733',3),('tgcr','734',3)
  ) as v(carrera, materia_cod, anio)
 where c.carrera = v.carrera and c.materia_cod = v.materia_cod;


-- Para comprobar a mano qué quedó cargado:
--   select carrera, count(*) filter (where publicado) as publicadas,
--          count(*) as todas, count(anio) as con_anio
--     from public.catedras group by carrera order by carrera;
