-- ============================================================
-- LOS AVISOS AL CELULAR
--
-- La alarma de inscripción es lo más útil que hace la app, y hasta
-- hoy tiene un agujero: solo avisa a quien ABRE la app. La ventana
-- para anotarse a una mesa dura cuatro días. Quien no entró en esos
-- cuatro días no se enteró de nada, y la app no tenía forma de
-- golpearle la puerta.
--
-- Esto es la puerta. Tres cosas separadas, y cada una se prende
-- aparte porque no todo el mundo quiere lo mismo:
--
--   mesas       «mañana cierra la inscripción». Sale sola de las
--               publicaciones, nadie la escribe a mano.
--   novedades   una novedad del panel, cuando quien la publica marca
--               que esa vale la pena avisarla. La mayoría no.
--   mis_fechas  «tu mesa de Trabajo Social I es en una semana», de
--               las preparaciones de final de cada quien. Necesita
--               cuenta: sin cuenta no hay preparaciones.
--
-- LO QUE SE GUARDA. Una suscripción es la dirección que el navegador
-- le da a la app para tocarle el timbre a ESE teléfono, más dos
-- claves con las que se cifra el mensaje. No hay nombre, no hay
-- teléfono, no hay correo. Sin cuenta, la fila no sabe de quién es.
--
-- POR QUÉ NADIE PUEDE LEER ESTA TABLA. La dirección de la suscripción
-- es un timbre abierto: con ella cualquiera le manda avisos al
-- teléfono de otra persona. Así que las tablas quedan cerradas con
-- llave para todo el mundo —ni siquiera quien inició sesión puede
-- hacerles un select— y lo único que entra son las dos funciones de
-- acá abajo, que escriben pero no dejan leer. Quien manda los avisos
-- entra por el costado, con la clave de servicio, que vive en
-- Supabase y no en el navegador.
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada.
--
-- ESTADO: aplicado en producción el 20/9/2026. Quedó verificado contra la
-- base (las dos tablas, las dos columnas de `publicaciones`, las tres
-- funciones, el disparador, el índice y RLS prendido sin policies) y contra
-- la API real (guardar un timbre sin cuenta anda; leer la tabla desde afuera
-- da «permission denied»; un endpoint inventado se rechaza).
--
-- POR QUÉ ESTO VA PRIMERO, ANTES DE SUBIR EL SITIO. Desde la v68 el panel
-- manda la columna `avisar` en CADA guardado de publicación. Si la columna
-- no existe, la base rechaza el guardado entero: no es que no suene el
-- teléfono, es que no se puede guardar ni editar NINGUNA publicación. Correr
-- esto no rompe nada de lo que ya está en el aire, así que siempre va antes.
--
-- Lo que falta (no es de este archivo): subir la función de Edge Functions,
-- cargar los tres secretos VAPID y prender el reloj de acá abajo.
-- ============================================================


-- ------------------------------------------------------------
-- 1. QUIÉN QUIERE QUE LE AVISEN
-- ------------------------------------------------------------
create table if not exists public.avisos_suscripciones (
  id          bigint generated by default as identity primary key,

  /* El timbre. Es única: el mismo teléfono que vuelve a prender los
     avisos pisa su fila vieja en vez de duplicarse. */
  endpoint    text not null unique,
  p256dh      text not null,
  auth        text not null,

  /* Null cuando prendió los avisos sin cuenta, que es el caso normal.
     Se llena solo si más adelante entra con su cuenta desde Mi perfil. */
  usuario_id  uuid references auth.users(id) on delete set null,

  mesas       boolean not null default true,
  novedades   boolean not null default true,
  mis_fechas  boolean not null default false,

  /* Para saber, cuando algo falle, si es «todos los iPhone» o «uno». */
  agente      text,

  /* Cuántas veces seguidas rebotó. A la tercera se borra sola: un
     timbre muerto que se sigue tocando es tiempo y cuota tirados. */
  fallos      int not null default 0,

  creado_at   timestamptz not null default now(),
  visto_at    timestamptz not null default now()
);

create index if not exists avisos_suscripciones_usuario_idx
  on public.avisos_suscripciones (usuario_id)
  where usuario_id is not null;


-- ------------------------------------------------------------
-- 2. QUÉ SE MANDÓ YA
--
-- El reloj corre cada hora, y cada hora vuelve a preguntar «¿mañana
-- cierra alguna inscripción?». Sin esta tabla, la respuesta sería que
-- sí quince veces y el teléfono sonaría quince veces.
--
-- La `clave` es el nombre del aviso, no el de la publicación:
-- 'mesa:12:cierra-manana' se manda una sola vez, pero
-- 'mesa:12:cierra-hoy' es otro aviso y sale igual al día siguiente.
-- ------------------------------------------------------------
create table if not exists public.avisos_enviados (
  suscripcion_id bigint not null
                 references public.avisos_suscripciones(id) on delete cascade,
  clave          text not null,
  enviado_at     timestamptz not null default now(),
  primary key (suscripcion_id, clave)
);

/* Lo viejo no sirve para nada y ocupa: se puede limpiar cuando se
   quiera con esto, o dejarlo, que tampoco pesa tanto.
   delete from public.avisos_enviados where enviado_at < now() - interval '120 days'; */


-- ------------------------------------------------------------
-- 3. QUÉ NOVEDAD SE AVISA
--
-- Por defecto NINGUNA. Avisar todo es la forma más rápida de que la
-- gente apague los avisos para siempre, y el que importa de verdad
-- —la inscripción— se pierde con el resto. Quien publica decide, de a
-- una, en el panel.
--
-- `avisar_at` es CUÁNDO se marcó, y no es un dato de auditoría: es lo
-- que le pone fecha de vencimiento al aviso. Solo sale en las 48 horas
-- siguientes a la marca. Sin eso, quien prende los avisos en marzo
-- recibe de golpe la novedad que alguien marcó en octubre, que ya no
-- se entiende y encima parece que la app está rota.
--
-- Lo pone el disparador, no el panel: una fecha que hay que acordarse
-- de escribir a mano es una fecha que alguna vez va a quedar vieja.
-- ------------------------------------------------------------
alter table public.publicaciones
  add column if not exists avisar    boolean not null default false,
  add column if not exists avisar_at timestamptz;

create or replace function public.marcar_cuando_se_aviso()
returns trigger
language plpgsql
-- Fijo, como las dos de abajo. Una funcion sin `search_path` propio usa el
-- de quien la llama, y eso deja la puerta a que alguien que pueda crear
-- objetos haga que `now()` sea otra cosa. Acá el riesgo es chico porque no
-- es `security definer`, pero el revisor de Supabase lo marca y no cuesta.
set search_path = public
as $fn$
begin
  /* Solo cuando pasa de «no» a «sí». Editar el título de una
     publicación ya marcada no reabre la ventana de 48 horas. */
  if new.avisar and (tg_op = 'INSERT' or not coalesce(old.avisar, false)) then
    new.avisar_at := now();
  elsif not new.avisar then
    new.avisar_at := null;
  end if;
  return new;
end;
$fn$;

drop trigger if exists publicaciones_avisar_at on public.publicaciones;
create trigger publicaciones_avisar_at
  before insert or update of avisar on public.publicaciones
  for each row execute function public.marcar_cuando_se_aviso();


-- ------------------------------------------------------------
-- 4. LAS DOS PUERTAS
--
-- `security definer` quiere decir que la función corre con los
-- permisos de quien la creó, no de quien la llama. Es lo que permite
-- que un teléfono sin cuenta escriba en una tabla que no puede ni
-- mirar. Por eso las dos son cortas y miran bien lo que reciben.
-- ------------------------------------------------------------

create or replace function public.guardar_aviso(
  p_endpoint   text,
  p_p256dh     text,
  p_auth       text,
  p_mesas      boolean default true,
  p_novedades  boolean default true,
  p_mis_fechas boolean default false,
  p_agente     text    default null
) returns void
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if p_endpoint is null or length(p_endpoint) < 20 or p_endpoint !~ '^https://' then
    raise exception 'endpoint invalido';
  end if;
  if p_p256dh is null or p_auth is null then
    raise exception 'faltan las claves';
  end if;

  insert into public.avisos_suscripciones
    (endpoint, p256dh, auth, usuario_id, mesas, novedades, mis_fechas, agente)
  values
    (p_endpoint, p_p256dh, p_auth, auth.uid(),
     coalesce(p_mesas, true), coalesce(p_novedades, true),
     coalesce(p_mis_fechas, false), left(coalesce(p_agente, ''), 300))
  on conflict (endpoint) do update set
    p256dh     = excluded.p256dh,
    auth       = excluded.auth,
    /* Si vuelve a guardar desde una pantalla sin sesión, NO se le
       borra la cuenta que ya tenía atada: se queda la de antes. */
    usuario_id = coalesce(auth.uid(), avisos_suscripciones.usuario_id),
    mesas      = excluded.mesas,
    novedades  = excluded.novedades,
    mis_fechas = excluded.mis_fechas,
    agente     = excluded.agente,
    fallos     = 0,
    visto_at   = now();
end;
$fn$;

create or replace function public.borrar_aviso(p_endpoint text)
returns void
language sql
security definer
set search_path = public
as $fn$
  delete from public.avisos_suscripciones where endpoint = p_endpoint;
$fn$;


-- ------------------------------------------------------------
-- 5. LOS CANDADOS
--
-- RLS prendido y NINGUNA policy: eso deja las tablas cerradas para
-- `anon` y para `authenticated`. No es un olvido, es la idea.
-- `service_role` pasa por arriba de RLS y es con lo que entra quien
-- manda los avisos.
-- ------------------------------------------------------------
alter table public.avisos_suscripciones enable row level security;
alter table public.avisos_enviados      enable row level security;

revoke all on public.avisos_suscripciones from anon, authenticated;
revoke all on public.avisos_enviados      from anon, authenticated;

grant execute on function public.guardar_aviso(text,text,text,boolean,boolean,boolean,text)
  to anon, authenticated;
grant execute on function public.borrar_aviso(text) to anon, authenticated;


-- ------------------------------------------------------------
-- 6. EL RELOJ
--
-- Esto NO se corre tal cual: hay que reemplazar **una sola cosa**, la que
-- está entre <>, y recién ahí pegarlo. La clave de servicio no va en este
-- archivo porque este archivo está en git. El código del proyecto ya está
-- puesto abajo.
--
--   <CLAVE-DE-SERVICIO>  Supabase -> Project Settings -> API ->
--          service_role. Es secreta: no se pega en ningún archivo
--          del repo, solo acá, una vez, en el SQL Editor.
--
-- Cada hora en punto. La función se fija sola la hora de Argentina y
-- no manda nada entre las 21 y las 9: un teléfono que suena a las
-- cuatro de la mañana se apaga para siempre al otro día.
-- ------------------------------------------------------------
-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- select cron.schedule(
--   'avisos-cada-hora',
--   '0 * * * *',
--   $CRON$
--   select net.http_post(
--     url     := 'https://kcgewgelfgyndbszfdep.supabase.co/functions/v1/avisos',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer <CLAVE-DE-SERVICIO>'),
--     body    := '{}'::jsonb
--   );
--   $CRON$
-- );
--
-- Para ver si corrió:
--   select * from cron.job_run_details order by start_time desc limit 10;
-- Para apagarlo:
--   select cron.unschedule('avisos-cada-hora');
