-- ============================================================
-- I° CONGRESO INTERDISCIPLINARIO · VOCES QUE HABITAN (octubre 2026)
--
-- La pantalla `congreso/`. Dos cosas distintas en la misma base:
--
--   LAS MESAS (`congreso_mesas`). El cronograma: título, fecha, hora,
--   aula, quién expone y la placa. Las carga y las cambia el equipo
--   desde el panel, porque un cambio de aula a las 11 de la mañana no
--   puede esperar a que alguien suba código. Cualquiera las lee.
--
--   LO QUE DICE LA GENTE (`congreso_intervenciones`). Dos tipos:
--     - «pregunta»: a quien expone, en una mesa. El resto la apoya con
--       ↑ y la que más apoyos tiene sube; quien modera lee de arriba.
--     - «aporte»: a uno de los tres ejes (salud, territorio,
--       tecnologías). Es lo que después sirve para las conclusiones.
--
-- Lo decidido con Máximo el 7/10/2026 y cómo queda acá:
--
--   SIN CUENTA. Al congreso viene gente de las tres carreras, docentes
--   y público de la región: pedir registrarse para hacer una pregunta
--   es perder la pregunta. El teléfono se reconoce con una MARCA al
--   azar, como en «Voy» (`sql/tabla-anotados.sql`), y la marca sirve
--   para dos cosas: un apoyo por teléfono, y el freno.
--
--   EL NOMBRE ES OPCIONAL. Si no lo ponen, la pantalla dice «Anónimo».
--
--   SALE AL TOQUE Y SE OCULTA DESPUÉS. En vivo, una pregunta que tarda
--   diez minutos en aprobarse llega cuando la mesa ya terminó. Así que
--   se publica sola, y el equipo o comunicación la ocultan desde el
--   panel si no corresponde. Oculta no se borra: queda, y se puede
--   volver a mostrar.
--
--   LA MARCA NO SE MUESTRA NUNCA. Las tablas están cerradas para
--   `anon` y `authenticated`; todo se lee y se escribe por funciones
--   `security definer` que devuelven el texto y el número de apoyos,
--   no quién lo mandó.
--
--   EL FRENO. Como la marca la inventa el teléfono, alguien podría
--   inventar mil. Hay tres topes: por teléfono (4 cada 2 minutos y 40
--   por día), por mesa o eje (300 por hora) y el mismo texto dos veces
--   seguidas no entra.
--
-- Quién modera: el mismo que el buzón, `modera_buzon()` (equipo y
-- comunicación, ver `sql/tabla-buzon.sql`). Quién edita las mesas:
-- solo el equipo, como el resto del cronograma de la app.
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada. Necesita que antes
-- esté `sql/tabla-buzon.sql` (de ahí sale `modera_buzon()`).
--
-- ESTADO: aplicado en producción el 7/10/2026 (lo corrió Máximo desde el
-- SQL Editor), después de un ensayo con begin/rollback y 20 pruebas de
-- permisos y del freno.
-- ============================================================


-- ------------------------------------------------------------
-- 1. LAS MESAS
-- ------------------------------------------------------------
create table if not exists public.congreso_mesas (
  id              bigint generated by default as identity primary key,
  -- «Voces que Habitan I, II, III…». Es el número de la placa, no el
  -- orden: el orden lo dan la fecha y la hora.
  numero          smallint check (numero between 1 and 99),
  titulo          text     not null check (length(btrim(titulo)) between 3 and 200),
  bajada          text     not null default '',
  -- Opcional: una mesa puede cruzar los tres ejes.
  eje             text     check (eje in ('salud', 'territorio', 'tecnologias')),
  fecha           date     not null,
  hora            time,
  lugar           text     not null default '',
  -- [ { "nombre": "Ana Fuks", "bio": "…" } ]
  expositores     jsonb    not null default '[]'::jsonb
                  check (jsonb_typeof(expositores) = 'array'),
  -- La placa de Instagram de esa mesa: una dirección completa (subida
  -- desde el panel) o una de `congreso/placas/`.
  placa           text,
  -- Quien modera puede cerrar las preguntas de una mesa (por ejemplo,
  -- cuando terminó la ronda) sin ocultar las que ya están.
  preguntas_abiertas boolean not null default true,
  publicada       boolean  not null default true,
  creado_at       timestamptz not null default now(),
  actualizado_at  timestamptz not null default now()
);

create index if not exists congreso_mesas_fecha_idx on public.congreso_mesas (fecha, hora);

alter table public.congreso_mesas enable row level security;

grant select on public.congreso_mesas to anon, authenticated;
grant insert, update, delete on public.congreso_mesas to authenticated;

-- Dos políticas y no una con «or»: `anon` no puede leer `perfiles`, y
-- Postgres no promete cortar el «or» antes de mirarla. Con una sola,
-- quien entra sin cuenta no veía ninguna mesa (lo encontró el ensayo
-- del 7/10/2026).
drop policy if exists "mesas lectura publica" on public.congreso_mesas;
create policy "mesas lectura publica" on public.congreso_mesas
  for select using (publicada);

drop policy if exists "mesas el equipo ve las borrador" on public.congreso_mesas;
create policy "mesas el equipo ve las borrador" on public.congreso_mesas
  for select to authenticated
  using (exists (select 1 from public.perfiles
                  where id = (select auth.uid()) and rol = 'equipo'));

drop policy if exists "mesas el equipo carga" on public.congreso_mesas;
create policy "mesas el equipo carga" on public.congreso_mesas
  for insert to authenticated
  with check (exists (select 1 from public.perfiles
                       where id = (select auth.uid()) and rol = 'equipo'));

drop policy if exists "mesas el equipo edita" on public.congreso_mesas;
create policy "mesas el equipo edita" on public.congreso_mesas
  for update to authenticated
  using (exists (select 1 from public.perfiles
                  where id = (select auth.uid()) and rol = 'equipo'));

drop policy if exists "mesas el equipo borra" on public.congreso_mesas;
create policy "mesas el equipo borra" on public.congreso_mesas
  for delete to authenticated
  using (exists (select 1 from public.perfiles
                  where id = (select auth.uid()) and rol = 'equipo'));

create or replace function public.tocar_congreso_mesa()
returns trigger language plpgsql as $$
begin
  new.actualizado_at = now();
  return new;
end $$;

drop trigger if exists al_tocar_congreso_mesa on public.congreso_mesas;
create trigger al_tocar_congreso_mesa before update on public.congreso_mesas
  for each row execute function public.tocar_congreso_mesa();


-- ------------------------------------------------------------
-- 2. LO QUE DICE LA GENTE, Y LOS APOYOS
-- ------------------------------------------------------------
create table if not exists public.congreso_intervenciones (
  id          bigint generated by default as identity primary key,
  tipo        text   not null check (tipo in ('pregunta', 'aporte')),
  mesa_id     bigint references public.congreso_mesas(id) on delete cascade,
  eje         text   check (eje in ('salud', 'territorio', 'tecnologias')),
  texto       text   not null check (length(texto) between 3 and 600),
  nombre      text   check (nombre is null or length(nombre) between 1 and 60),
  marca       text   not null check (marca ~ '^[0-9a-f]{32}$'),
  oculta      boolean not null default false,
  respondida  boolean not null default false,
  creado_at   timestamptz not null default now(),
  -- Una pregunta es de una mesa; un aporte es de un eje. Nunca las dos.
  check ((tipo = 'pregunta' and mesa_id is not null and eje is null)
      or (tipo = 'aporte'   and eje is not null and mesa_id is null))
);

create index if not exists congreso_interv_mesa_idx
  on public.congreso_intervenciones (mesa_id) where mesa_id is not null;
create index if not exists congreso_interv_eje_idx
  on public.congreso_intervenciones (eje) where eje is not null;
create index if not exists congreso_interv_marca_idx
  on public.congreso_intervenciones (marca, creado_at);

create table if not exists public.congreso_votos (
  intervencion_id bigint not null references public.congreso_intervenciones(id) on delete cascade,
  marca           text   not null check (marca ~ '^[0-9a-f]{32}$'),
  creado_at       timestamptz not null default now(),
  primary key (intervencion_id, marca)
);

create index if not exists congreso_votos_marca_idx on public.congreso_votos (marca, creado_at);

alter table public.congreso_intervenciones enable row level security;
alter table public.congreso_votos          enable row level security;

-- Cerradas del todo. Sin políticas a propósito: todo pasa por las
-- funciones de abajo, que no devuelven la marca.
revoke all on public.congreso_intervenciones from anon, authenticated;
revoke all on public.congreso_votos          from anon, authenticated;


-- ------------------------------------------------------------
-- 3. LEER EL MURO
--
-- Una mesa (sus preguntas) o un eje (sus aportes). Ordenado por
-- apoyos y después por la más vieja, que es como lee quien modera: la
-- que más le interesa a la sala, y entre iguales la que llegó antes.
--
-- Quien modera ve también las ocultas, marcadas, para poder volver a
-- mostrarlas. `modera_buzon()` mira la sesión: sin cuenta da falso.
-- ------------------------------------------------------------
create or replace function public.congreso_muro(
  p_mesa bigint default null,
  p_eje  text   default null
) returns table (
  id bigint, tipo text, mesa_id bigint, eje text, texto text, nombre text,
  respondida boolean, oculta boolean, apoyos bigint, creado_at timestamptz
)
language sql stable security definer set search_path = public as $$
  select i.id, i.tipo, i.mesa_id, i.eje, i.texto, i.nombre,
         i.respondida, i.oculta,
         (select count(*) from public.congreso_votos v where v.intervencion_id = i.id),
         i.creado_at
    from public.congreso_intervenciones i
   where ((p_mesa is not null and i.mesa_id = p_mesa)
       or (p_eje  is not null and i.eje = p_eje))
     and (not i.oculta or public.modera_buzon())
     and (i.mesa_id is null or exists (select 1 from public.congreso_mesas m
                                        where m.id = i.mesa_id and m.publicada))
   order by 9 desc, i.creado_at asc
   limit 400;
$$;

revoke all on function public.congreso_muro(bigint, text) from public;
grant execute on function public.congreso_muro(bigint, text) to anon, authenticated;


-- ------------------------------------------------------------
-- 4. MANDAR UNA PREGUNTA O UN APORTE
-- ------------------------------------------------------------
create or replace function public.congreso_intervenir(
  p_tipo   text,
  p_mesa   bigint,
  p_eje    text,
  p_texto  text,
  p_nombre text,
  p_marca  text
) returns bigint
language plpgsql security definer set search_path = public as $fn$
declare
  v_texto  text := btrim(regexp_replace(coalesce(p_texto, ''), '\s+', ' ', 'g'));
  v_nombre text := nullif(btrim(coalesce(p_nombre, '')), '');
  v_id     bigint;
begin
  if p_marca is null or p_marca !~ '^[0-9a-f]{32}$' then
    raise exception 'marca invalida';
  end if;
  if length(v_texto) < 3 then
    raise exception 'el texto es muy corto';
  end if;
  if length(v_texto) > 600 then
    raise exception 'el texto es muy largo';
  end if;
  if v_nombre is not null and length(v_nombre) > 60 then
    v_nombre := left(v_nombre, 60);
  end if;

  if p_tipo = 'pregunta' then
    /* Se puede preguntar desde que la mesa está publicada hasta el día
       siguiente: quien no llegó a hacerla en la sala la deja igual. */
    if not exists (select 1 from public.congreso_mesas m
                    where m.id = p_mesa and m.publicada and m.preguntas_abiertas
                      and m.fecha >= current_date - 1) then
      raise exception 'las preguntas de esta mesa estan cerradas';
    end if;
  elsif p_tipo = 'aporte' then
    if p_eje is null or p_eje not in ('salud', 'territorio', 'tecnologias') then
      raise exception 'eje invalido';
    end if;
  else
    raise exception 'tipo invalido';
  end if;

  /* El freno, de más chico a más grande. */
  if (select count(*) from public.congreso_intervenciones
       where marca = p_marca and creado_at > now() - interval '2 minutes') >= 4 then
    raise exception 'esperá un ratito antes de mandar otra';
  end if;
  if (select count(*) from public.congreso_intervenciones
       where marca = p_marca and creado_at > now() - interval '1 day') >= 40 then
    raise exception 'llegaste al tope de hoy';
  end if;
  if exists (select 1 from public.congreso_intervenciones
              where marca = p_marca and lower(texto) = lower(v_texto)
                and creado_at > now() - interval '1 day') then
    raise exception 'ya mandaste eso';
  end if;
  if (select count(*) from public.congreso_intervenciones
       where (case when p_tipo = 'pregunta' then mesa_id = p_mesa else eje = p_eje end)
         and creado_at > now() - interval '1 hour') >= 300 then
    raise exception 'demasiadas por hora';
  end if;

  insert into public.congreso_intervenciones (tipo, mesa_id, eje, texto, nombre, marca)
  values (p_tipo,
          case when p_tipo = 'pregunta' then p_mesa end,
          case when p_tipo = 'aporte'   then p_eje  end,
          v_texto, v_nombre, p_marca)
  returning id into v_id;

  return v_id;
end;
$fn$;

revoke all on function public.congreso_intervenir(text, bigint, text, text, text, text) from public;
grant execute on function public.congreso_intervenir(text, bigint, text, text, text, text) to anon, authenticated;


-- ------------------------------------------------------------
-- 5. APOYAR (Y DESAPOYAR)
--
-- Un apoyo por teléfono. Devuelve cuántos tiene, así la pantalla no
-- pide el muro entero de nuevo.
-- ------------------------------------------------------------
create or replace function public.congreso_apoyar(
  p_id     bigint,
  p_marca  text,
  p_quiero boolean default true
) returns bigint
language plpgsql security definer set search_path = public as $fn$
begin
  if p_marca is null or p_marca !~ '^[0-9a-f]{32}$' then
    raise exception 'marca invalida';
  end if;
  if not exists (select 1 from public.congreso_intervenciones
                  where id = p_id and not oculta) then
    raise exception 'no esta';
  end if;

  if p_quiero then
    if (select count(*) from public.congreso_votos
         where marca = p_marca and creado_at > now() - interval '1 hour') >= 200 then
      raise exception 'demasiados apoyos por hora';
    end if;
    insert into public.congreso_votos (intervencion_id, marca)
    values (p_id, p_marca) on conflict do nothing;
  else
    delete from public.congreso_votos where intervencion_id = p_id and marca = p_marca;
  end if;

  return (select count(*) from public.congreso_votos where intervencion_id = p_id);
end;
$fn$;

revoke all on function public.congreso_apoyar(bigint, text, boolean) from public;
grant execute on function public.congreso_apoyar(bigint, text, boolean) to anon, authenticated;


-- ------------------------------------------------------------
-- 6. MODERAR
--
-- Ocultar, volver a mostrar, y marcar como respondida (la respondida
-- sigue a la vista, pero baja y se ve tachada: la sala sabe que ya
-- pasó). Solo equipo y comunicación.
-- ------------------------------------------------------------
create or replace function public.congreso_moderar(
  p_id         bigint,
  p_oculta     boolean default null,
  p_respondida boolean default null
) returns void
language plpgsql security definer set search_path = public as $fn$
begin
  if not public.modera_buzon() then
    raise exception 'solo quien modera';
  end if;
  update public.congreso_intervenciones
     set oculta     = coalesce(p_oculta, oculta),
         respondida = coalesce(p_respondida, respondida)
   where id = p_id;
end;
$fn$;

revoke all on function public.congreso_moderar(bigint, boolean, boolean) from public, anon;
grant execute on function public.congreso_moderar(bigint, boolean, boolean) to authenticated;


-- ------------------------------------------------------------
-- 7. EL CRONOGRAMA QUE YA SE CONOCE (7/10/2026)
--
-- Sale de las placas de Instagram. Solo se carga si la tabla está
-- vacía: después manda lo que se edite en el panel.
--
-- Falta «Voces que Habitan II»: no estaba entre las placas.
-- Los ejes de III y IV no los dice la placa: quedan sin eje hasta que
-- alguien los ponga en el panel.
-- ------------------------------------------------------------
insert into public.congreso_mesas (numero, titulo, bajada, eje, fecha, hora, lugar, expositores, placa)
select * from (values
  (1::smallint, 'Derecho a la salud: ¿qué puede la APS?',
   'Territorios, prácticas y cuidados en debate.', 'salud',
   date '2026-10-09', time '12:00', 'Aula Magna',
   '[{"nombre":"Ale Wagner"},{"nombre":"Ana Fuks"},{"nombre":"Cynthia Ramacciotti"}]'::jsonb,
   'placas/mesa-1.webp'),
  (3::smallint, 'Trabajo Social y la justicia hoy',
   'Transformaciones, tensiones y desafíos para la intervención.', null,
   date '2026-10-14', time '14:30', 'Aula 14',
   '[{"nombre":"Luciana Ponziani"},{"nombre":"Marcela Velurtas"},{"nombre":"Analía Chillemi"}]'::jsonb,
   'placas/mesa-3.webp'),
  (4::smallint, 'Niñeces e intervención fonoaudiológica',
   '', null,
   date '2026-10-16', time '18:00', 'Aula 14',
   '[{"nombre":"Silvia Cesanelli"},{"nombre":"Gisele Prado"}]'::jsonb,
   'placas/mesa-4.webp'),
  (5::smallint, '¿La IA puede reemplazarnos?',
   'Nuevas subjetividades e intervención profesional.', 'tecnologias',
   date '2026-10-22', time '13:00', 'Aula Magna',
   '[{"nombre":"Verónica Sforzin"},{"nombre":"Javier"},{"nombre":"Daniel T"}]'::jsonb,
   'placas/mesa-5.webp'),
  (6::smallint, 'Experiencias de gestión comunitaria del riesgo',
   'Con el CEPA (Cuerpo de Evacuación y Primeros Auxilios, La Plata), en conjunto con la cátedra Estado, Territorio y Problemáticas Sociales.', 'territorio',
   date '2026-10-22', time '17:00', 'Aula 4',
   '[{"nombre":"CEPA La Plata"}]'::jsonb,
   'placas/mesa-6.webp')
) as v(numero, titulo, bajada, eje, fecha, hora, lugar, expositores, placa)
where not exists (select 1 from public.congreso_mesas);
