-- ============================================================
-- LAS PUBLICACIONES  ·  la agenda, el calendario y la portada
--
-- Es la tabla más leída de la app y hasta hoy era la única importante
-- SIN su archivo acá: se creó a mano en el SQL Editor y sus permisos
-- quedaron repartidos, parte sin escribir en ningún lado y parte
-- adentro de `sql/tabla-buzon.sql` (las del rol `comunicacion`).
-- Este archivo la junta entera. Lo de `tabla-buzon.sql` queda viejo:
-- las políticas de abajo lo reemplazan, y correr este archivo alcanza.
--
-- De acá salen tres cosas, sin que ninguna tenga tabla propia:
--   la lista de la agenda      (`agenda/index.html`, dibujar)
--   el calendario del mes      (`agenda/index.html`, montarCal)
--   «lo próximo» de la portada (`index.html`, proximoDeLaAgenda)
-- Por eso una fila bien cargada aparece en los tres lugares sola, y no
-- hace falta tocar pantallas para que un evento nuevo se vea.
--
-- QUIÉN ESCRIBE. Dos roles, y la diferencia es el punto de todo esto:
--
--   equipo        -> todo. Es el panel completo.
--   comunicacion  -> un rol liviano (nació con el buzón). Carga
--                    novedades, y desde hoy también EVENTOS: los paros
--                    y los grupos de estudio, que son lo que más se
--                    mueve y lo que más gente necesita poder cargar.
--
-- LO QUE LA BASE GARANTIZA SOBRE LOS EVENTOS DE `comunicacion`, para
-- que no dependa de que la pantalla esté bien hecha:
--
--   grupo de estudio (linea = 'saberes') -> puede entrar publicado.
--   paro             (linea = 'gremial') -> hasta el 30/9/2026 entraba
--                    sin publicar y lo aprobaba el equipo. Desde la
--                    sección 9 se publica directo; ver ahí por qué.
--   actividad        (linea = 'frente')  -> desde el 30/9, igual.
--   ninguno marca `avisar`: los eventos avisan solos, por categoría
--   (sección 8 y `supabase/functions/avisos`).
--   ninguno toca la alarma de mesas (`alarma = 'ninguna'`).
--
-- POR QUÉ `alarma = 'ninguna'` NO SE NEGOCIA. Lo encontró el
-- /security-review del 24/9: la app y la función de avisos MIRAN EL
-- TÍTULO, así que una publicación llamada «Inscripción a la mesa…»
-- haría sonar la alarma de mesas en todos los teléfonos. Además de
-- forzar la columna, los eventos de `comunicacion` no pueden empezar
-- con esos títulos. Son dos candados para el mismo agujero.
--
-- Cómo se corre:
--   supabase.com -> proyecto "La Bolivar con vos" -> SQL Editor
--   -> New query -> pegar todo esto -> Run
-- Se puede correr más de una vez sin romper nada.
--
-- OJO CON LOS DOS CANDADOS, como en el resto de la app: el GRANT dice
-- si un rol puede tocar la tabla y la RLS dice qué filas. Si solo se
-- escriben las políticas RLS, da error 42501 y no anda nada.
-- ============================================================


-- ============================================================
-- 1. LA TABLA
--
-- Escrita tal como está hoy en la base (se leyó el 29/9/2026), así el
-- archivo sirve para rearmarla de cero en un proyecto nuevo. En el
-- proyecto que ya existe, ninguno de estos `if not exists` hace nada.
-- ============================================================

create table if not exists public.publicaciones (
  id          bigint generated by default as identity primary key,
  tipo        text not null default 'novedad',
  linea       text not null default 'info',
  titulo      text not null,
  cuerpo      text,
  fecha_desde date,
  fecha_hasta date,
  hora        text,
  lugar       text,
  imagen_url  text,
  link_url    text,
  destacado   boolean not null default false,
  publicado   boolean not null default true,
  creado_at   timestamptz not null default now(),
  alarma      text,
  periodo     text,
  avisar      boolean not null default false,
  avisar_at   timestamptz
);

-- `evento` es un paro, un grupo de estudio, una charla: algo con fecha
-- y lugar. `fecha` es una fecha clave del calendario académico.
-- `novedad` es lo que no tiene fecha propia.
alter table public.publicaciones drop constraint if exists publicaciones_tipo_check;
alter table public.publicaciones add constraint publicaciones_tipo_check
  check (tipo in ('novedad', 'evento', 'fecha'));

alter table public.publicaciones drop constraint if exists publicaciones_linea_check;
alter table public.publicaciones add constraint publicaciones_linea_check
  check (linea in ('frente', 'gremial', 'info', 'saberes'));

-- Si alimenta la alarma de mesas, tiene que decir de qué mesa.
alter table public.publicaciones drop constraint if exists publicaciones_alarma_valida;
alter table public.publicaciones add constraint publicaciones_alarma_valida
  check (alarma is null or alarma = 'ninguna'
         or (alarma in ('inscripcion', 'mesa')
             and periodo is not null and btrim(periodo) <> ''));


-- ============================================================
-- 2. QUIÉN CARGÓ CADA COSA  ·  columna nueva
--
-- Hace falta para moderar: si un paro entra sin publicar y alguien del
-- equipo lo tiene que aprobar, tiene que poder ver quién lo mandó. Y
-- para que quien carga pueda borrar lo SUYO sin poder tocar lo de otro.
--
-- Queda en null en todo lo cargado hasta hoy, y eso está bien: no se
-- puede inventar el autor de algo viejo. `on delete set null` para que
-- borrar una cuenta no se lleve publicaciones puestas.
-- ============================================================

alter table public.publicaciones
  add column if not exists creado_por uuid
  references auth.users(id) on delete set null;

-- Se llena sola con quien está logueado: así no depende de que la
-- pantalla se acuerde de mandarla, y la política de abajo obliga a que
-- sea el que escribe, así que tampoco se puede falsear desde el cliente.
alter table public.publicaciones
  alter column creado_por set default auth.uid();

create index if not exists publicaciones_creado_por_idx
  on public.publicaciones (creado_por) where creado_por is not null;

-- La bandeja de paros esperando visto bueno entra por acá.
create index if not exists publicaciones_pendientes_idx
  on public.publicaciones (creado_at desc)
  where publicado = false;


-- ============================================================
-- 3. LOS DOS CANDADOS  ·  grants y RLS
-- ============================================================

alter table public.publicaciones enable row level security;

grant select on public.publicaciones to anon, authenticated;
grant insert, update, delete on public.publicaciones to authenticated;

-- Quien no tiene cuenta solo LEE. Hasta hoy `anon` tenía los cuatro
-- permisos: no se podía escribir igual, porque ninguna política RLS se
-- lo permitía, pero era un candado de más abierto al gusto. Se cierra.
revoke insert, update, delete on public.publicaciones from anon;


-- ============================================================
-- 4. LEER
-- ============================================================

-- Sin cuenta se ve solo lo publicado. Un paro esperando visto bueno no
-- se ve en la app: es justamente lo que lo hace seguro.
drop policy if exists "publicaciones_lectura" on public.publicaciones;
create policy "publicaciones_lectura"
  on public.publicaciones for select to anon, authenticated
  using (publicado);

drop policy if exists "publicaciones_lectura_equipo" on public.publicaciones;
create policy "publicaciones_lectura_equipo"
  on public.publicaciones for select to authenticated
  using (public.es_equipo());


-- ============================================================
-- 5. EL EQUIPO  ·  todo
-- ============================================================

drop policy if exists "publicaciones_escritura" on public.publicaciones;
create policy "publicaciones_escritura"
  on public.publicaciones for all to authenticated
  using (public.es_equipo())
  with check (public.es_equipo());


-- ============================================================
-- 6. `comunicacion`  ·  novedades y eventos
--
-- Reemplaza las cuatro políticas que hoy están en `tabla-buzon.sql`
-- acotadas a `tipo = 'novedad'`. Los nombres son los mismos a propósito:
-- el `drop policy if exists` de cada una las pisa, así correr este
-- archivo deja una sola versión y no dos que se sumen.
-- ============================================================

-- Qué puede cargar y editar, en una sola función para no repetir la
-- condición en tres políticas y que se despeguen con el tiempo.
create or replace function public.publicacion_de_comunicacion(
  p_tipo      text,
  p_linea     text,
  p_titulo    text,
  p_alarma    text,
  p_avisar    boolean,
  p_publicado boolean
) returns boolean language sql immutable as $$
  select
    coalesce(p_alarma, '') = 'ninguna'
    and (
      -- Las novedades siguen como estaban (pueden avisar al celular:
      -- así las usa el buzón desde el 24/9).
      p_tipo = 'novedad'
      or (
        p_tipo = 'evento'
        -- Un evento no hace sonar teléfonos ni se parece a una mesa.
        and p_avisar = false
        and p_titulo !~* '^\s*(inscripci[óo]n a la mesa|mesa de examen)'
        and (
             p_linea = 'saberes'                          -- grupo de estudio
          or (p_linea = 'gremial' and p_publicado = false) -- paro: lo publica el equipo
        )
      )
    );
$$;

revoke all on function public.publicacion_de_comunicacion(text,text,text,text,boolean,boolean)
  from public, anon;
grant execute on function public.publicacion_de_comunicacion(text,text,text,text,boolean,boolean)
  to authenticated;

-- VE lo suyo aunque no esté publicado: el que manda un paro tiene que
-- poder ver en qué quedó.
drop policy if exists "publicaciones comunicacion ve novedades" on public.publicaciones;
create policy "publicaciones comunicacion ve novedades"
  on public.publicaciones for select to authenticated
  using (public.es_comunicacion()
         and (tipo in ('novedad', 'evento') or creado_por = auth.uid()));

drop policy if exists "publicaciones comunicacion carga novedades" on public.publicaciones;
create policy "publicaciones comunicacion carga novedades"
  on public.publicaciones for insert to authenticated
  with check (public.es_comunicacion()
              and creado_por = auth.uid()
              and public.publicacion_de_comunicacion(
                    tipo, linea, titulo, alarma, avisar, publicado));

-- Edita, pero no puede pasar un paro a publicado: la condición también
-- se pide DESPUÉS del cambio (`with check`).
drop policy if exists "publicaciones comunicacion edita novedades" on public.publicaciones;
create policy "publicaciones comunicacion edita novedades"
  on public.publicaciones for update to authenticated
  using (public.es_comunicacion()
         and public.publicacion_de_comunicacion(
               tipo, linea, titulo, alarma, avisar, publicado))
  with check (public.es_comunicacion()
              and public.publicacion_de_comunicacion(
                    tipo, linea, titulo, alarma, avisar, publicado));

-- Borra las novedades (como hasta hoy) y los eventos QUE CARGÓ ÉL. Un
-- compañero tiene que poder deshacer su propio error sin poder borrar
-- el grupo de estudio de otro.
drop policy if exists "publicaciones comunicacion borra novedades" on public.publicaciones;
create policy "publicaciones comunicacion borra novedades"
  on public.publicaciones for delete to authenticated
  using (public.es_comunicacion()
         and (tipo = 'novedad'
              or (tipo = 'evento' and creado_por = auth.uid())));


-- ============================================================
-- 7. DAR DE ALTA A QUIEN VA A CARGAR
--
-- La persona crea su cuenta desde la app como cualquier estudiante y,
-- después, en el SQL Editor:
--
--   update public.perfiles set rol = 'comunicacion'
--   where id = (select id from auth.users where email = 'elcorreo@ejemplo.com');
--
-- Para ver quiénes pueden cargar hoy:
--   select p.rol, u.email from public.perfiles p
--     join auth.users u on u.id = p.id
--    where p.rol in ('equipo', 'comunicacion') order by p.rol;
--
-- Para ver los paros esperando visto bueno:
--   select id, titulo, fecha_desde, creado_at from public.publicaciones
--    where publicado = false and tipo = 'evento' order by creado_at;
-- ============================================================


-- ============================================================
-- 8. CATEGORÍAS, SUSPENDER Y LAS MARCAS DE LOS AVISOS  ·  30/9/2026
--
-- Propuesta 3, tanda 1 (`docs/PROPUESTAS.md`). Hasta hoy un paro y un
-- grupo de estudio eran los dos `tipo = 'evento'`: se veían iguales,
-- no se podían filtrar por separado y no había cómo avisar solo uno.
--
--   categoria    lo que ve la estudiante: paro, grupo, actividad,
--                fecha (académica) o comunicado. `tipo` y `linea` se
--                quedan: las políticas de abajo los usan, y un
--                teléfono con el panel viejo en caché los sigue
--                mandando sin `categoria`.
--   materia      de qué materia es un grupo de estudio. Es con lo que
--                la función de avisos elige a quién le suena.
--   suspendido   se suspende sin borrar: lo borrado desaparece y
--                nadie se entera; lo suspendido queda tachado en la
--                agenda y avisa.
--   publicado_at cuándo empezó a verse. Es lo que abre la ventana del
--                aviso «nuevo». `creado_at` no sirve: un paro viejo
--                que el equipo aprueba hoy es nuevo HOY.
--   cambiado_at  cuándo cambió algo que obliga a avisar (día, hora,
--                lugar, suspendido). Editar una coma no cuenta.
--
-- Las dos marcas y la categoría las pone el disparador, no la
-- pantalla, por lo mismo que `avisar_at`: una fecha que hay que
-- acordarse de mandar es una fecha que alguna vez falta.
-- ============================================================

alter table public.publicaciones
  add column if not exists categoria    text,
  add column if not exists materia      text,
  add column if not exists suspendido   boolean not null default false,
  add column if not exists publicado_at timestamptz,
  add column if not exists cambiado_at  timestamptz;

-- Lo cargado antes de hoy. Un paro era un evento gremial y un grupo un
-- evento de saberes: así los cargaba `cargar/`, así que la cuenta sale
-- exacta. `publicado_at = creado_at` deja lo viejo FUERA de la ventana
-- del aviso «nuevo»: correr esto no hace sonar ningún teléfono.
update public.publicaciones set categoria = case
    when tipo = 'fecha'   then 'fecha'
    when tipo = 'novedad' then 'comunicado'
    when linea = 'gremial' then 'paro'
    when linea = 'saberes' then 'grupo'
    else 'actividad' end
  where categoria is null;

update public.publicaciones set publicado_at = creado_at
  where publicado and publicado_at is null;

-- Corrección del 30/9: tres grupos de estudio cargados desde el panel
-- con la línea gremial habían quedado como paros por la regla de arriba.
update public.publicaciones
   set categoria = 'grupo',
       materia = coalesce(materia, nullif(btrim(regexp_replace(titulo,
                   '^\s*grupo de estudio\s*(de|:)?\s*', '', 'i'), ' .'), ''))
 where tipo = 'evento' and categoria <> 'grupo' and titulo ~* '^\s*grupo de estudio';

-- Los grupos cargados desde `cargar/` tienen la materia en el título.
update public.publicaciones
   set materia = btrim(substr(titulo, length('Grupo de estudio de ') + 1))
 where categoria = 'grupo' and materia is null
   and titulo ilike 'Grupo de estudio de %';

alter table public.publicaciones drop constraint if exists publicaciones_categoria_check;
alter table public.publicaciones add constraint publicaciones_categoria_check
  check (categoria in ('paro', 'grupo', 'actividad', 'fecha', 'comunicado'));

-- La categoría no puede contradecir al tipo. Sin esto, alguien con el
-- rol liviano podía cargar una NOVEDAD con `categoria = 'paro'` y
-- hacerla sonar en todos los teléfonos como si fuera un paro.
alter table public.publicaciones drop constraint if exists publicaciones_categoria_coherente;
alter table public.publicaciones add constraint publicaciones_categoria_coherente
  check (   (categoria in ('paro', 'grupo', 'actividad') and tipo = 'evento')
         or (categoria = 'fecha'      and tipo = 'fecha')
         or (categoria = 'comunicado' and tipo = 'novedad'));

alter table public.publicaciones drop constraint if exists publicaciones_materia_largo;
alter table public.publicaciones add constraint publicaciones_materia_largo
  check (materia is null or length(materia) <= 120);

create or replace function public.marcas_de_publicacion()
returns trigger
language plpgsql
set search_path = public
as $fn$
begin
  /* Sin categoría (panel o `cargar/` viejos en caché), se deduce igual
     que en el `update` de arriba. */
  if new.categoria is null then
    new.categoria := case
      when new.tipo = 'fecha'    then 'fecha'
      when new.tipo = 'novedad'  then 'comunicado'
      /* Antes que la línea: en el panel se cargaron grupos de estudio
         con la línea gremial, y quedaban como paros (30/9/2026). */
      when new.titulo ~* '^\s*grupo de estudio' then 'grupo'
      when new.linea = 'gremial' then 'paro'
      when new.linea = 'saberes' then 'grupo'
      else 'actividad' end;
  end if;

  if new.publicado and (tg_op = 'INSERT' or not coalesce(old.publicado, false)) then
    new.publicado_at := now();
  elsif not new.publicado then
    new.publicado_at := null;
  end if;

  /* Solo lo que ya se estaba viendo puede «cambiar»: lo que se edita
     antes de publicarse sale con el aviso de nuevo, ya corregido. */
  if tg_op = 'UPDATE' and new.publicado and coalesce(old.publicado, false)
     and (new.fecha_desde is distinct from old.fecha_desde
       or new.fecha_hasta is distinct from old.fecha_hasta
       or new.hora        is distinct from old.hora
       or new.lugar       is distinct from old.lugar
       or new.suspendido  is distinct from old.suspendido) then
    new.cambiado_at := now();
  end if;

  return new;
end;
$fn$;

drop trigger if exists publicaciones_marcas on public.publicaciones;
create trigger publicaciones_marcas
  before insert or update on public.publicaciones
  for each row execute function public.marcas_de_publicacion();

create index if not exists publicaciones_avisos_idx
  on public.publicaciones (publicado_at desc)
  where publicado and categoria in ('paro', 'grupo', 'actividad');


-- ============================================================
-- 9. `comunicacion` PUBLICA DIRECTO, Y SOLO TOCA LO SUYO  ·  30/9/2026
--
-- Decidido el 30/9: los paros ya no esperan visto bueno. Lo que antes
-- cuidaba la espera ahora lo cuidan tres cosas:
--   - solo carga quien tiene el rol (con cuenta, y queda `creado_por`),
--   - cada quien edita y suspende LO SUYO, no lo de otro,
--   - corregir o suspender manda el aviso de cambio a quien ya tenía
--     el aviso de nuevo.
-- Se suma la tercera clase de evento, la actividad (charla, asamblea,
-- jornada), que va con la línea del frente.
-- ============================================================

create or replace function public.publicacion_de_comunicacion(
  p_tipo      text,
  p_linea     text,
  p_titulo    text,
  p_alarma    text,
  p_avisar    boolean,
  p_publicado boolean
) returns boolean language sql immutable as $$
  select
    coalesce(p_alarma, '') = 'ninguna'
    and (
      p_tipo = 'novedad'
      or (
        p_tipo = 'evento'
        -- `avisar` sigue apagado: los eventos avisan solos, por
        -- categoría, desde la función `avisos`. La marca manual es de
        -- los comunicados.
        and p_avisar = false
        and p_titulo !~* '^\s*(inscripci[óo]n a la mesa|mesa de examen)'
        and p_linea in ('saberes', 'gremial', 'frente')
      )
    );
$$;

-- Lo marcaba el revisor de Supabase (search_path cambiable). No es
-- `security definer`, así que el riesgo es chico, pero no cuesta.
alter function public.publicacion_de_comunicacion(text,text,text,text,boolean,boolean)
  set search_path = public;

-- Edita novedades como hasta hoy, y eventos solo los que cargó.
drop policy if exists "publicaciones comunicacion edita novedades" on public.publicaciones;
create policy "publicaciones comunicacion edita novedades"
  on public.publicaciones for update to authenticated
  using (public.es_comunicacion()
         and (tipo = 'novedad' or creado_por = auth.uid())
         and public.publicacion_de_comunicacion(
               tipo, linea, titulo, alarma, avisar, publicado))
  with check (public.es_comunicacion()
              and (tipo = 'novedad' or creado_por = auth.uid())
              and public.publicacion_de_comunicacion(
                    tipo, linea, titulo, alarma, avisar, publicado));
