-- ============================================================
-- «VOY» Y «ME ANOTO»  ·  sin cuenta, y solo se cuenta
--
-- Propuestas 2 y 3 (tanda 3), `docs/PROPUESTAS.md`. En cualquier evento
-- de la agenda (paro, grupo de estudio, actividad) hay un botón «Voy»;
-- en los grupos dice «Me anoto». Quien lo toca:
--
--   - suma uno al contador público («van 12»), que es lo que le sirve a
--     quien organiza para pedir un aula del tamaño justo;
--   - recibe los avisos de ESE evento (el del día y el de cambio o
--     suspensión) aunque tenga apagado el canal de esa categoría;
--   - en un grupo, ve el enlace del grupo de WhatsApp si lo hay, y puede
--     dejar su número, opcional, para que lo sumen.
--
-- Lo decidido el 29/9 (propuesta 2) y cómo queda acá:
--
--   SIN CUENTA. Quien más necesita el grupo es quien menos ganas tiene
--   de registrarse. El teléfono se reconoce con una MARCA al azar que
--   guarda la app (`bolivar-voy`), y esa marca es la que desanota. No
--   hay nombre ni correo.
--
--   SOLO SE CUENTA. `anotados` no tiene ninguna columna con datos de
--   nadie, y aun así nadie puede leerla: el contador sale de la vista
--   `anotados_totales`, con el mismo patrón que `buzon_totales`.
--
--   EL TIMBRE NO SE COPIA. Si el teléfono tiene los avisos prendidos,
--   la app manda su endpoint; la base busca la fila en
--   `avisos_suscripciones` y guarda SOLO el número de fila, como hace el
--   buzón. El endpoint no queda en esta tabla.
--
--   EL NÚMERO, APARTE Y CON FECHA DE VENCIMIENTO. `anotados_contacto`
--   es el único dato personal de todo esto: lo ve solo quien cargó ese
--   grupo (RLS por fila, ni el resto del equipo), se deja solo estando
--   anotado, y se borra solo dos días después del encuentro.
--
--   SIN CUPO. El botón no se apaga nunca.
--
-- Todo entra por funciones `security definer` que miran lo que reciben;
-- las tablas están cerradas para `anon` y `authenticated`.
--
-- Cómo se corre:
--   supabase.com -> proyecto -> SQL Editor -> New query -> pegar -> Run
-- Se puede correr más de una vez sin romper nada.
--
-- ESTADO: aplicado en producción el 30/9/2026 (migración `tabla_anotados`),
-- después de un ensayo con begin/rollback y 22 pruebas de permisos.
-- ============================================================


-- ------------------------------------------------------------
-- 1. LAS DOS TABLAS
-- ------------------------------------------------------------
create table if not exists public.anotados (
  id              bigint generated by default as identity primary key,
  publicacion_id  bigint not null references public.publicaciones(id) on delete cascade,
  marca           text   not null check (marca ~ '^[0-9a-f]{32}$'),
  suscripcion_id  bigint references public.avisos_suscripciones(id) on delete set null,
  creado_at       timestamptz not null default now(),
  unique (publicacion_id, marca)
);

create index if not exists anotados_suscripcion_idx
  on public.anotados (suscripcion_id) where suscripcion_id is not null;

create table if not exists public.anotados_contacto (
  id              bigint generated by default as identity primary key,
  publicacion_id  bigint not null references public.publicaciones(id) on delete cascade,
  marca           text   not null check (marca ~ '^[0-9a-f]{32}$'),
  telefono        text   not null check (telefono ~ '^\+?[0-9][0-9 ()-]{6,22}$'),
  creado_at       timestamptz not null default now(),
  unique (publicacion_id, marca)
);


-- ------------------------------------------------------------
-- 2. LOS CANDADOS
-- ------------------------------------------------------------
alter table public.anotados          enable row level security;
alter table public.anotados_contacto enable row level security;

revoke all on public.anotados          from anon, authenticated;
revoke all on public.anotados_contacto from anon, authenticated;

-- Quien cargó el grupo lee los números de SU grupo, y nadie más: ni el
-- resto del equipo, ni `comunicacion`. Es una política por fila, no una
-- pantalla que filtra.
grant select on public.anotados_contacto to authenticated;
drop policy if exists "quien organiza ve los numeros" on public.anotados_contacto;
create policy "quien organiza ve los numeros" on public.anotados_contacto
  for select to authenticated
  using (exists (select 1 from public.publicaciones p
                  where p.id = publicacion_id and p.creado_por = (select auth.uid())));


-- ------------------------------------------------------------
-- 3. EL CONTADOR PÚBLICO
-- ------------------------------------------------------------
create or replace function public.anotados_totales_calc()
returns table (publicacion_id bigint, cuantos bigint)
language sql stable security definer set search_path = public as $$
  select a.publicacion_id, count(*)
    from public.anotados a
    join public.publicaciones p on p.id = a.publicacion_id and p.publicado
   group by a.publicacion_id;
$$;

revoke all on function public.anotados_totales_calc() from public;
grant execute on function public.anotados_totales_calc() to anon, authenticated;

create or replace view public.anotados_totales
  with (security_invoker = on) as
  select * from public.anotados_totales_calc();

revoke all on public.anotados_totales from anon, authenticated;
grant select on public.anotados_totales to anon, authenticated;


-- ------------------------------------------------------------
-- 4. LAS PUERTAS
--
-- Las tres devuelven cuántos van, así la pantalla no pide dos veces.
-- ------------------------------------------------------------

-- ¿Se puede anotar a esto? Publicado, un evento, y que no haya pasado.
create or replace function public.anotable(p_publicacion bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.publicaciones p
     where p.id = p_publicacion and p.publicado and not p.suspendido
       and p.categoria in ('paro', 'grupo', 'actividad')
       and coalesce(p.fecha_hasta, p.fecha_desde, current_date) >= current_date - 1);
$$;
revoke all on function public.anotable(bigint) from public, anon, authenticated;

create or replace function public.anotarme(
  p_publicacion bigint,
  p_marca       text,
  p_endpoint    text default null
) returns bigint
language plpgsql security definer set search_path = public as $fn$
declare
  v_suscripcion bigint;
begin
  if p_marca is null or p_marca !~ '^[0-9a-f]{32}$' then
    raise exception 'marca invalida';
  end if;
  if not public.anotable(p_publicacion) then
    raise exception 'no se puede anotar a esto';
  end if;

  /* El freno. La marca la inventa el teléfono, así que alguien podría
     inventar mil: un tope por publicación y por hora hace que inflar el
     número cueste más que lo que vale. */
  if (select count(*) from public.anotados
       where publicacion_id = p_publicacion
         and creado_at > now() - interval '1 hour') >= 300 then
    raise exception 'demasiados por hora';
  end if;

  if p_endpoint is not null and length(p_endpoint) between 20 and 1000 then
    select id into v_suscripcion from public.avisos_suscripciones
     where endpoint = p_endpoint;
  end if;

  insert into public.anotados (publicacion_id, marca, suscripcion_id)
  values (p_publicacion, p_marca, v_suscripcion)
  on conflict (publicacion_id, marca) do update
    set suscripcion_id = coalesce(excluded.suscripcion_id, anotados.suscripcion_id);

  return (select count(*) from public.anotados where publicacion_id = p_publicacion);
end;
$fn$;

create or replace function public.desanotarme(p_publicacion bigint, p_marca text)
returns bigint
language plpgsql security definer set search_path = public as $fn$
begin
  delete from public.anotados
   where publicacion_id = p_publicacion and marca = p_marca;
  /* Desanotarse se lleva el número también: se dejó para ESE grupo. */
  delete from public.anotados_contacto
   where publicacion_id = p_publicacion and marca = p_marca;
  return (select count(*) from public.anotados where publicacion_id = p_publicacion);
end;
$fn$;

create or replace function public.dejar_contacto(
  p_publicacion bigint,
  p_marca       text,
  p_telefono    text
) returns void
language plpgsql security definer set search_path = public as $fn$
declare
  v_tel text := btrim(coalesce(p_telefono, ''));
begin
  /* Solo quien está anotado, y solo en un grupo de estudio. */
  if not exists (select 1 from public.anotados
                  where publicacion_id = p_publicacion and marca = p_marca) then
    raise exception 'primero hay que anotarse';
  end if;
  if not exists (select 1 from public.publicaciones
                  where id = p_publicacion and categoria = 'grupo') then
    raise exception 'solo en los grupos de estudio';
  end if;

  if v_tel = '' then
    delete from public.anotados_contacto
     where publicacion_id = p_publicacion and marca = p_marca;
    return;
  end if;

  insert into public.anotados_contacto (publicacion_id, marca, telefono)
  values (p_publicacion, p_marca, v_tel)
  on conflict (publicacion_id, marca) do update set telefono = excluded.telefono;
end;
$fn$;

revoke all on function public.anotarme(bigint, text, text)          from public;
revoke all on function public.desanotarme(bigint, text)             from public;
revoke all on function public.dejar_contacto(bigint, text, text)    from public;
grant execute on function public.anotarme(bigint, text, text)       to anon, authenticated;
grant execute on function public.desanotarme(bigint, text)          to anon, authenticated;
grant execute on function public.dejar_contacto(bigint, text, text) to anon, authenticated;


-- ------------------------------------------------------------
-- 5. LOS NÚMEROS SE BORRAN SOLOS
--
-- Dos días después del encuentro. Un número pedido para avisar de un
-- grupo del martes no tiene por qué seguir ahí en marzo.
-- ------------------------------------------------------------
create extension if not exists pg_cron;

select cron.schedule(
  'borrar-contactos-viejos',
  '17 4 * * *',
  $CRON$
  delete from public.anotados_contacto c
   using public.publicaciones p
   where p.id = c.publicacion_id
     and coalesce(p.fecha_hasta, p.fecha_desde, c.creado_at::date) < current_date - 2;
  $CRON$
);
